### ISSUE TITLE
[FEATURE] Support text embedding processor

### ISSUE THREAD

**Issue by miguel-vila** [opensearch-project/opensearch-java#1005]
Not sure if I missed something in the `org.opensearch.client.opensearch.ingest.Processor` class, but it seems there's no constructor for the [text embedding](https://opensearch.org/docs/latest/ingest-pipelines/processors/text-embedding/) processor as specified [here](https://opensearch.org/docs/latest/ingest-pipelines/processors/text-embedding/). But, looking at the [OpenAPI spec](https://github.com/opensearch-project/opensearch-api-specification/blob/69247b090197cb49b159dd68277002417fbab84f/spec/schemas/ingest._common.yaml#L33), it seems it's missing from there as well.

Am I missing something? Does the Java client depend on the OpenAPI spec?

**Comment by dblock** [comment]
> Am I missing something? Does the Java client depend on the OpenAPI spec?

Not yet. We have a PR up for that from @Xtansia and fully expect that to get finished and merged shortly. #366 - Take a look?

**Comment by dblock** [comment]
> But, looking at the [OpenAPI spec](https://github.com/opensearch-project/opensearch-api-specification/blob/69247b090197cb49b159dd68277002417fbab84f/spec/schemas/ingest._common.yaml#L33), it seems it's missing from there as well.

Can you contribute it to the spec? You can also hand-roll the code in opensearch-java for it now if you want it in faster.

**Comment by miguel-vila** [comment]
here's the spec PR: opensearch-project/opensearch-api-specification#304
