### ISSUE TITLE
[BUG] Avoid reflection in pathEncode

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#1008]
### What is the bug?

In https://github.com/opensearch-project/opensearch-java/pull/999 we are using reflection to call `pathEncode` from the right library. There be dragons.

### What is the expected behavior?

Do not use reflection.

Alternatives attempted were to use a common library. A better approach is likely to change the class hierarchy so that the active transport library is doing the encoding.

**Comment by Xtansia** [comment]
Resolved by #1109
