### ISSUE TITLE
[FEATURE] SearchResponse doesn't include status i.e. RestStatus

### ISSUE THREAD

**Issue by dishatkr** [opensearch-project/opensearch-java#1009]
### Is your feature request related to a problem?

I’m moving from restHighLevelClient V2.5 to Openserach java Client V2.5
In the SearchResponse of RestHighLevelClient, there is a method to know the status Code returned by Opensearch.

### Do you have any additional context?

**From RestHighLevelClient** - https://github.com/opensearch-project/OpenSearch/blob/fffd1010e88baf332f2dd4169d69bfcf0a869780/server/src/main/java/org/opensearch/action/search/SearchResponse.java#L199

We don’t see any similar method in the **SearchResponse** of **Opensearch Java Client**. What could be the alternative to get the status in this case ?
https://github.com/opensearch-project/opensearch-java/blob/db50b7d6089c6fbc988736863b36368d2a8cdad4/java-client/src/main/java/org/opensearch/client/opensearch/core/SearchResponse.java

**Comment by dblock** [comment]
I think this is a dup of https://github.com/opensearch-project/opensearch-java/issues/824. AFAIK there's no current way to do this and an implementation would be much appreciated! Note that the generic client that was added recently does have access to the entire request/response, which may be an acceptable workaround.

**Comment by dblock** [comment]
Closing as dup.
