### ISSUE TITLE
[RELEASE] Release v. Next

### ISSUE THREAD

**Issue by BrendonFaleiro** [opensearch-project/opensearch-java#1047]
Can we get a release of 2.10.5 with the fix for https://github.com/opensearch-project/opensearch-java/issues/1042?

**Comment by dblock** [comment]
That would be a 2.11.1, we did a 2.11 release a few days ago.

**Comment by BrendonFaleiro** [comment]
ETA?

**Comment by dblock** [comment]
I will try to get to this in the next couple of days unless someone beats me to it. 

There's a bunch of open bugs and issues in this project, could use some help!

**Comment by Xtansia** [comment]
@BrendonFaleiro v2.11.1 has been released to maven including this fix, please let me know if you run into any issues with it!
