### ISSUE TITLE
[FEATURE] add a module-info.java to support JPMS properly

### ISSUE THREAD

**Issue by SingingBush** [opensearch-project/opensearch-java#108]
I'm currently trying to build a modular jar of my app that depends on:

```
<dependency>
    <groupId>org.opensearch.client</groupId>
    <artifactId>opensearch-rest-high-level-client</artifactId>
    <version>1.2.4</version>
    <scope>compile</scope>
</dependency>
```

but as the opensearch java clients don't have _module-info.java_ files it's defaulting to try and do the modularity based on the classes in the file. This would potentially be okay if it wasn't for the fact that the _org.opensearch.client_ package is available in two places.

```
module myapp reads package org.opensearch.client from both opensearch.rest.high.level.client and opensearch.rest.client
```

This is probably something that can be solved by properly supporting the module system.

**Comment by reta** [comment]
@SingingBush you may check https://github.com/opensearch-project/OpenSearch/issues/1838, `opensearch-rest-high-level-client` depends on quite a few core modules which have to be modularized first

**Comment by SingingBush** [comment]
thanks for linking the existing ticket. The split packages problem will certainly need to be solved. I also noticed that the high level client pulls in a lot of transient dependencies that probably aren't needed.
