### ISSUE TITLE
[BUG]  FieldSort not implement SortOptionsVariant

### ISSUE THREAD

**Issue by jbrun** [opensearch-project/opensearch-java#1089]
### What is the bug?
When we want to sort a request, FieldSort doesn’t implement SortOptionVariant, so we cannot use it in SearchRequest with SortOptionsBuilders

### How can one reproduce the bug?
`SearchRequest.Builder searchRequest = new SearchRequest.Builder()
.sort(SortOptionsBuilders.field().field(“lastName”).order(SortOrder.Desc).build()._toSortOptions());`

or

`SearchRequest.Builder searchRequest = new SearchRequest.Builder()
.sort(FieldSort.of(s → s.field(“lastName”).order(ortOrder.Desc))._toSortOptions());`

._toSortOptions() not available

However ScoreSort, GeoDistanceSort and ScriptSort implement SortOptionVariant

### What is the expected behavior?
package org.opensearch.client.opensearch._types;
public class FieldSort implements **SortOptionsVariant**, JsonpSerializable

### What is your host/environment?
opensearch-java:2.10.4

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/amistrn)]
