### ISSUE TITLE
[BUG] Publish snapshot workflows intermittently failing

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#1090]
### What is the bug?

Looking at https://github.com/opensearch-project/opensearch-java/actions/workflows/publish-snapshots.yml many workflows fail with a 403.

### How can one reproduce the bug?

https://github.com/opensearch-project/opensearch-java/actions/workflows/publish-snapshots.yml

### What is the expected behavior?

Workflows to all be green.

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/amistrn)]

**Comment by Xtansia** [comment]
Workflow was run without issue for >2months
