### ISSUE TITLE
[RELEASE] Release v. Next

### ISSUE THREAD

**Issue by jordanpadams** [opensearch-project/opensearch-java#1093]
Can we get a new tagged release of the library per bug fix #1068? This is a blocker for our AOSS migration efforts.

If this is a lot of effort, [fixing this bug with publishing this SNAPSHOT](https://github.com/opensearch-project/opensearch-java/issues/1090) would at least allow us to get out an interim build. Thanks!

**Comment by dblock** [comment]
Tagging @Xtansia for a release, or I can take care of it early next week.

@jordanpadams want to try and help with the fix for the SNAPSHOT workflow?

**Comment by jordanpadams** [comment]
@dblock the 403 forbidden indicates an issue with the login information, which I do not have access to. It needs to be updated either with the correct username/password, or it may need to be a generated set of tokens generated through Sonatype: https://central.sonatype.org/publish/generate-token/

**Comment by dblock** [comment]
2.12.0 was released, https://github.com/opensearch-project/opensearch-java/releases/tag/v2.12.0

**Comment by tloubrieu-jpl** [comment]
Hi @dblock ,

Something does not seems right with the release.

The bug https://github.com/opensearch-project/opensearch-java/issues/1068 we wanted to fix is not fixed in the release (according to my tests).

And, randomly, I also noticed that the following commit https://github.com/opensearch-project/opensearch-java/commit/373802683b0380985d6f246218d2e1b051c8f394 is not in the release.

Do you have an idea why that is ?

Thanks

**Comment by Xtansia** [comment]
@tloubrieu-jpl I can confirm from decompiling the 2.12.0 jar from Maven that it does contain the changes from PR #1072. Can you please confirm your POM/Gradle/etc. configuration and which version of the dependency you are taking?

It will not contain commit 3738026 as that is only going in the next major release (3.0.0) as it is a breaking change.

**Comment by tloubrieu-jpl** [comment]
Thanks @Xtansia , I captured the maven dependencies of my project there:

```
 +- org.opensearch.client:opensearch-java:jar:2.12.0:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.eclipse.parsson:parsson:jar:1.1.6:compile
[INFO] |  |  \- jakarta.json:jakarta.json-api:jar:2.1.3:compile
[INFO] |  +- org.opensearch.client:opensearch-rest-client:jar:2.12.0:runtime
[INFO] |  +- jakarta.json.bind:jakarta.json.bind-api:jar:2.0.0:runtime
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.17.0:runtime
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.17.0:runtime
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.0:runtime
[INFO] |  |  \- net.bytebuddy:byte-buddy:jar:1.14.9:runtime
[INFO] |  \- org.eclipse:yasson:jar:2.0.2:runtime
[INFO] |     \- org.glassfish:jakarta.json:jar:module:2.0.0:runtime
```
I could retest by building from branch `v2.*.*` to compare the behavior with the release `2.12.0`.

**Comment by tloubrieu-jpl** [comment]
I've built the jar from branch `2.x` and our test for bug https://github.com/opensearch-project/opensearch-java/issues/1068 is failing, but works on branch `main`

I think @workmanw developed integration tests for that bug. Do they run with command `./gradlew clean build -x test`.

**Comment by workmanw** [comment]
@tloubrieu-jpl You'll need an AOSS collection and authenticated creditionals.

```
./gradlew integrationTest --tests "*AwsSdk2*" -Dtests.awsSdk2support.domainHost=....us-west-2.aoss.amazonaws.com -Dtests.awsSdk2support.domainRegion=us-west-2 -Dtests.awsSdk2support.serviceName=aoss
```

Note that if you're using SSO based auth you'll also need to include that jar into the build.

**Comment by tloubrieu-jpl** [comment]
> @tloubrieu-jpl You'll need an AOSS collection and authenticated creditionals.
> 
> ```
> ./gradlew integrationTest --tests "*AwsSdk2*" -Dtests.awsSdk2support.domainHost=....us-west-2.aoss.amazonaws.com -Dtests.awsSdk2support.domainRegion=us-west-2 -Dtests.awsSdk2support.serviceName=aoss
> ```
> 
> Note that if you're using SSO based auth you'll also need to include that jar into the build.

Thanks @workmanw , I am getting this error when I run the integration test as you proposed:

```
AwsSdk2AsyncStacktraceIT > testFailureFromClientPreservesStacktraceOfCaller FAILED
    java.lang.AssertionError at AwsSdk2AsyncStacktraceIT.java:24
        Caused by: java.lang.NoClassDefFoundError at AwsSdk2AsyncStacktraceIT.java:24
            Caused by: java.lang.ClassNotFoundException at AwsSdk2AsyncStacktraceIT.java:24
```

I am completelly new to `gradle`. Is there a dependency missing somewhere ?
