### ISSUE TITLE
[BUG] Deserializing a custom normalizer without type specified fails

### ISSUE THREAD

**Issue by Blomex** [opensearch-project/opensearch-java#1110]
### What is the bug?
It is possible to manually create a custom normalizer without the type property explicitly specified. Attempting to deserialize this with the client such as when retrieving the index with client.indices.get() it will fail due to no type property. The server's logic is that type must be specified unless tokenizer is specified in which case type: "custom" is assumed.

### How can one reproduce the bug?
```
PUT /custom-normalizer-index
{
  "mappings": {
    "properties": {
      "text_chunk": {
        "type": "keyword",
        "normalizer": "case_insensitive"
      }
    }
  },
  "settings": {
    "analysis": {
      "normalizer": {
        "case_insensitive": {
          "filter": "lowercase"
        }
      }
    }
  }
}
```
client.indices().get(b -> b.index("custom-normalizer-index"))

### What is the expected behavior?
Analyzer to successfully deserialize as a CustomNormalizer

### What is your host/environment?
MacOS Sonoma 14.5

### Do you have any screenshots?
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/f10b5836-7097-4545-ab21-c6ff33812928">

### Do you have any additional context?

Issue is very similiar to https://github.com/opensearch-project/opensearch-java/issues/1032, but for normalizer instead of analyzer.

**Comment by Xtansia** [comment]
This was released as part of 2.13.0: https://central.sonatype.com/artifact/org.opensearch.client/opensearch-java/2.13.0
