### ISSUE TITLE
[BUG] AOSS does not match localhost again now for DeleteByQueryRequest

### ISSUE THREAD

**Issue by al-niessner** [opensearch-project/opensearch-java#1112]
### What is the bug?
This construct works using docker opensearch image 2.13.0 at localhost (httpClient5) while AOSS (httpClient5 also since 3.0.0-SNAPSHOT) terminates with a 404. 

### How can one reproduce the bug?
```
      DeleteByQueryRequest dbqr = new DeleteByQueryRequest.Builder()
      .index("db")
      .query(new Query.Builder().term(new TermQuery.Builder()
          .field("uid")
          .value(new FieldValue.Builder().stringValue("a:b:c::2.0").build())
          .build()).build())
      .build();
```

Full executable test code available on request but it is 100+ lines adding noise to signal.

### What is the expected behavior?
AOSS and localhost should behave identicallty.

### What is your host/environment?
Ubuntu, opensearch 3.0.0-SNAPSHOT 2024-07-24

### Do you have any screenshots?
No.

### Do you have any additional context?
Updated EndpointTest to see if it related to previous problems. It does not appear to be:
```
      DeleteByQueryRequest dbqr = new DeleteByQueryRequest.Builder()
      .index("db")
      .query(new Query.Builder().term(new TermQuery.Builder()
          .field("uid")
          .value(new FieldValue.Builder().stringValue("a:b:c::2.0").build())
          .build()).build())
      .build();
      assertEquals("/db/_delete_by_query", DeleteByQueryRequest._ENDPOINT.requestUrl(dbqr));
```

This check passes most notably because the query is not passed via URL. Hence not the same as previous issues. If we then look at dbqr.toJsonString() 
`{"query":{"term":{"uid":{"value":"a:b:c::2.0"}}}}` it should be immune to URL encoding.

Does testing for the full URL in use require a different mechanism other than `_ENCODING.requestUrl()`? Something else strange happening like DBQR fetches the data then has hard time with ':' in id?

**Comment by al-niessner** [comment]
Related issue: NASA-PDS/registry-mgr#78

**Comment by dblock** [comment]
I believe `delete_by_query` is [not supported by Amazon OpenSearch Serverless](https://repost.aws/questions/QUzT6LZt1qRGKNyPJQRV20PQ/does-opensearch-serverless-support-delete-by-query), hence a 404. I'm sure the team is aware about it, but I would reach out to Amazon customer support to bubble the ask for the feature.

Should this be closed?

**Comment by al-niessner** [comment]
Please keep it open until we here back from AWS please. Once verified, we can close it.

**Comment by al-niessner** [comment]
Operation not supported by AOSS with suggestion to delete by collection.
