### ISSUE TITLE
[BUG] NodeInfoRequest fails when connecting to Amazon OpenSearch Service 

### ISSUE THREAD

**Issue by dancristiancecoi** [opensearch-project/opensearch-java#1129]
### What is the bug?
When sending a NodeInfoRequest to Amazon OpenSearch Service the request fails with the following error:

`Missing required property 'NodeInfo.host'`

This issue appears to be caused by  Amazon OpenSearch Service obfuscating/removing some fields from the REST API responses that the client code expects to be not null.

Beside NodeInfo.host the following fields are also missing from the response and are causing a similar error:

- NodeInfo.IP
- NodeInfo.TransportAddress

### How can one reproduce the bug?

1. Connect the client to Amazon OpenSearch Service with basic auth and only fine-grained access control enabled (IAM is disabled).
2.  Send a NodeInfoRequest:
```
   NodesInfoRequest nodesInfoRequest = new NodesInfoRequest.Builder().metric(List.of("plugins")).build();
   NodesInfoResponse nodesInfoResponse = openSearchNodesClient.info(nodesInfoRequest);
```

### Do you have any additional context?

I can raise a PR with a fix which consists in removing _requireNonNull_ from these specific fields.

**Comment by dblock** [comment]
Thanks for opening this @dancristiancecoi. Removing the null constraint is likely the right move. As we are working on generating much of this code from spec in #366, please also check https://github.com/opensearch-project/opensearch-api-specification for correctness?

**Comment by dancristiancecoi** [comment]
@dblock I think we can remove these two fields from the [required list](https://github.com/opensearch-project/opensearch-api-specification/blob/cfe357b7f066933991daab7ba4bf5840d9fd8546/spec/schemas/nodes.info.yaml#L104) if my findings are actually correct and its not due to a misconfiguration on my part. Cheers!

**Comment by dancristiancecoi** [comment]
> > @dblock I think we can remove these two fields from the [required list](https://github.com/opensearch-project/opensearch-api-specification/blob/cfe357b7f066933991daab7ba4bf5840d9fd8546/spec/schemas/nodes.info.yaml#L104) if my findings are actually correct and its not due to a misconfiguration on my part. Cheers!
> 
> Is the only way to reproduce this behavior to run against AWS serverless? Either way care to contribute the fix into the spec, please?

I have only seen this issue with Amazon OpenSearch Service. Have not tested Serverless but I suspect it will have a similar behavior.  

And sure, I will raise an issue & PR.

**Comment by dancristiancecoi** [comment]
PR merged

**Comment by dancristiancecoi** [comment]
PR merged.

**Comment by Xtansia** [comment]
v2.14.0 has been released and includes the fix for this issue
