### ISSUE TITLE
[FEATURE] Add query_image to Neural query

### ISSUE THREAD

**Issue by urinud** [opensearch-project/opensearch-java#1137]
### Is your feature request related to a problem?
Server side of Neural Query has an option to query_image which is not available in Java Client implementation.

### What solution would you like?
Add to NeuralQuery class imageQuery field and its corresponding serialization.

### What alternatives have you considered?
Create a local class, inherit and use it instead of the existing one. But its better to collaborate with the project.

### Do you have any additional context?
None.

**Comment by Xtansia** [comment]
v2.14.0 has been released and includes the fix for this issue
