### ISSUE TITLE
Remove references to deprecated service: JCenter 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-java#114]
From https://github.com/opensearch-project/opensearch-build/issues/1456 and  https://discuss.opendistrocommunity.dev/t/jcenter-build-issues/8293

> _What’s the problem?_
> JCenter, which is a repository used in our builds, ceased operations today. Gradle was pulling dependencies from JCenter, and some repos have a direct dependency on it. This broke that the build process for OpenSearch engine, all branches so that the last successful build of 1.3 was at 7:03 AM PT Jan 12th.

References in this repository, [query](https://github.com/search?q=repo%3Aopensearch-project%2Fopensearch-java+jcenter%28%29&type=code).

**Comment by VachaShah** [comment]
Done as part of #120.
