### ISSUE TITLE
[BUG] timeZone not implemented in CompositeDateHistogramAggregationSource

### ISSUE THREAD

**Issue by yyj1219** [opensearch-project/opensearch-java#1142]
### What is the bug?
timeZone not implemented in CompositeDateHistogramAggregationSource.

### How can one reproduce the bug?
```java
CompositeDateHistogramAggregationSource.of(cdha -> cdha
        .field("time")
        .fixedInterval(Time.of(t -> t.time("1h")))
        .timeZone("Asia/Seoul")
);
```

I expected `timeZone()`, but there is `zoneId()`. 
However, in OpenSearch 2.13, `CompositeDateHistogramAggregationSource` only supports `time_zone` and does not support `zone_id`.

### What is the expected behavior?
Please add `timeZone()`.

### What is your host/environment?
OpenSearch 2.13 and OpenSearch Java Client 2.13

**Comment by NodleKang** [comment]
@Xtansia Alright, I'll give it a try.

**Comment by yyj1219** [comment]
@Xtansia Alright, I'll give it a try.
