### ISSUE TITLE
[BUG] When Query Types That Extend `QueryBase` Are Converted To Builders Inherited Data Is Lost

### ISSUE THREAD

**Issue by PiSoup** [opensearch-project/opensearch-java#1172]
### What is the bug?
Calling `.toBuilder()` on a query such as `MatchQuery` will lose the `queryName` and `boost` fields that are inherited from `QueryBase`. Odds are this is true for many other query types though I've not audited them all.

### How can one reproduce the bug?
An example modified version of MatchQueryTest which sets `queryName` will fail.
```
    @Test
    public void toBuilder() {
        MatchQuery origin = new MatchQuery.Builder().field("field").query(FieldValue.of("1")).queryName("name").build();
        MatchQuery copied = origin.toBuilder().build();

        assertEquals(toJson(copied), toJson(origin));
    }
```

**Comment by Xtansia** [comment]
That's a good catch @PiSoup! Thanks for reporting this. Would you be interested in helping to fix this?

**Comment by PiSoup** [comment]
I'd be delighted. I'll take a look next week.

**Comment by PiSoup** [comment]
Opened the PR https://github.com/opensearch-project/opensearch-java/pull/1181. I only updated the match test since the change is identical for all the query types.
