### ISSUE TITLE
[FEATURE] Test against latest SNAPSHOTs of OpenSearch v. Next

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#123]
**Is your feature request related to a problem?**

In https://github.com/opensearch-project/opensearch-java/pull/122 we have added integration tests against released versions of OpenSearch. We'd like to catch bugs for the next version of OpenSearch earlier.
  
**What solution would you like?**
Add -SNAPSHOT/latest builds of OpenSearch to the matrix. As the time of writing this would be 1.3.1 and 2.0. Ignore failures (continue-on-error) so that these tests don't block PRs.

**Comment by VachaShah** [comment]
Working on this.

**Comment by VachaShah** [comment]
Added as part of #139
