### ISSUE TITLE
[FEATURE] Support data_type property for KnnVectorProperty

### ISSUE THREAD

**Issue by andrewrchen05** [opensearch-project/opensearch-java#1254]
### Is your feature request related to a problem?
Binary vectors are supported but data_type is not a property for KnnVector

### What solution would you like?
I want `data_type` to be supported in the KnnVectorProperty in the Java Client so I can call GetIndex to verify the data_type of an index https://javadoc.io/doc/org.opensearch.client/opensearch-java/latest/org/opensearch/client/opensearch/_types/mapping/KnnVectorProperty.html

```
                "vector": {
                    "type": "knn_vector",
                    "dimension": 1024,
                    "data_type": "binary",
                    "method": {
                        "engine": "faiss",
                        "space_type": "hamming",
                        "name": "hnsw",
                        "parameters": {}
                    }
                }
```

### What alternatives have you considered?
Using generic client

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dblock** [comment]
I see it [here](https://github.com/opensearch-project/opensearch-api-specification/blob/931a61ae023b453e3611f37a802ef27b9c4877a1/spec/schemas/_common.mapping.yaml#L1142) in the API spec so codegen will pick it up with some more work.
