### ISSUE TITLE
[BUG] testClusterGetSettingsWithDefault fails intermittently

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#127]
**What is the bug?**

See https://github.com/opensearch-project/opensearch-java/runs/5645720812?check_suite_focus=true, tests failed on main against 1.3.0.

**What is the expected behavior?**
Tests pass.

**Comment by reta** [comment]
Fails randomly (flaky?):

```
> Task :java-client:integrationTest

org.opensearch.client.opensearch.integTest.ClusterClientIT > testClusterGetSettingsWithDefault FAILED
    java.lang.AssertionError at ClusterClientIT.java:159

36 tests completed, 1 failed

> Task :java-client:integrationTest FAILED
```

**Comment by dblock** [comment]
It failed again in https://github.com/opensearch-project/opensearch-java/pull/131#pullrequestreview-926687067, retried, and it passed.
