### ISSUE TITLE
[FEATURE] add batch_size parameter in text_embedding processor

### ISSUE THREAD

**Issue by YeonghyeonKO** [opensearch-project/opensearch-java#1297]
### Is your feature request related to a problem?
From [OpenSearch 2.16](https://opensearch.org/blog/introducing-opensearch-2-16/), it's possible to add [batch inference support](https://opensearch.org/docs/latest/ml-commons-plugin/api/model-apis/batch-predict/) in ingest processors which inherits from AbstractBatchingProcessor(https://github.com/opensearch-project/neural-search/pull/820). From now on, OpenSearch java client doesn't support **batch_size** parameter(optional) when defining **text_embedding** processor.

### What solution would you like?
- Add **batch_size** parameter in **text_embedding** processor which already exists.
- If the above action were merged, the next step would be including **SparseEncodingProcessor** in opensearch-java client.

**Comment by Xtansia** [comment]
@YeonghyeonKO your fix for this was released in v2.18.0 of the client
