### ISSUE TITLE
[BUG] Tag for v1.0.0 is missing and no GitHub Releases.

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-java#149]
**What is the bug?**

There is no tag created as 1.0.0 released `https://search.maven.org/artifact/org.opensearch.client/opensearch-java`; this will be confusing and difficult for users to know that this client has been formally released. 

**How can one reproduce the bug?**
- Go to the repo page and see there is no Releases on the right side.
- Go to the tag page and there is no tag cut for v1.0.0.

**What is the expected behavior?**
Both the tag and Release should be present. 

**Do you have any screenshots?**
Tag:
<img width="1279" alt="Screen Shot 2022-04-14 at 3 01 52 PM" src="https://user-images.githubusercontent.com/87548827/163483594-b0a01c10-7305-44d6-8235-e35eb4e2d07d.png">
Release:
<img width="317" alt="Screen Shot 2022-04-14 at 3 01 42 PM" src="https://user-images.githubusercontent.com/87548827/163483598-24ea8093-38c2-425d-9b29-61f9f04875e5.png">

**Comment by VachaShah** [comment]
Added the tag and the release https://github.com/opensearch-project/opensearch-java/releases/tag/v1.0.0
