### ISSUE TITLE
[BUG] can't sort on field when document of that field contains null. fixed in elasticsearch-java.

### ISSUE THREAD

**Issue by joelbolt35** [opensearch-project/opensearch-java#158]
**What is the bug?**
A full convo can be found here regarding the bug:
https://discuss.elastic.co/t/failure-with-sorts-and-new-co-elastic-clients-elasticsearch-java-client/291511/12

tl;dr: Sorting on a field where documents contain null breaks.

**What is the expected behavior?**
I am able to sort on a field where some documents contain NULL in those fields.

**Elastic Searches Fix**
https://github.com/elastic/elasticsearch-java/pull/68/files

**Comment by dblock** [comment]
@joelbolt35 Please feel free to reimplement a fix in this project. If you do, please confirm that you're not copying from non-APLv2 elasticsearch-java.

**Comment by chibenwa** [comment]
Hello there,

As a notice, on a migration effort for Apache James to OpenSearch, with the rest client 2.0.0 and OpenSearch 2.0.0 we encouter the issue...

https://github.com/Arsnael/james-project/blob/970ef4dce2f48f581376ace450dc5891f3f0ef7b/mailbox/opensearch/src/test/java/org/apache/james/mailbox/opensearch/ElasticSearchIntegrationTest.java#L426

**Comment by Arsnael** [comment]
Hi guys! 

Tried to take a crack at it as mentioned by my friend above we encountered that issue too. I took an approach completely different from the fix from es so I don't think it should be an issue.

Cheers!

**Comment by Arsnael** [comment]
Thanks for merging it team! Just want to know when can we expect a next release of the client with the fix?

**Comment by dblock** [comment]
I believe we can close this with https://github.com/opensearch-project/opensearch-java/pull/169. 

We usually release clients along with the server, cc: @CEHENKLE

**Comment by Arsnael** [comment]
> We usually release clients along with the server, cc: @CEHENKLE

@dblock No offense but I saw other clients, even the high level java one, having a 2.0.1 release along with the server already, but this one didn't follow up it seems (2.0.0 still being the latest). Should I be worried?

**Comment by dblock** [comment]
@Arsnael I think we didn't release 2.0.1 because it wasn't needed. The 2.0 release works with 2.0.1.

I do understand that you want this bug fix released. Maybe we should start doing this more methodically? Care to open an issue saying "Release v. Next" and say "I need bug fix XYZ" or something like that?
