### ISSUE TITLE
Release version 2.0.0 for Java client

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-java#159]
Release the client version 2.0.0. Before releasing, the following items need to be done:

- [x] Use OpenSearch 2.0 in [gradle](https://github.com/opensearch-project/opensearch-java/blame/e14fb59fa7582521f84d5283e39c0aeb86fb3a45/java-client/build.gradle.kts#L126) dependencies in place of the snapshot version. 
- [x] Add OpenSearch 2.0 to the integration [test matrix](https://github.com/opensearch-project/opensearch-java/blob/main/.github/workflows/test-integration.yml#L17).
- [x] Bump the client version to 2.0.0.
- [x] Cut a 2.0 branch for the client.

**Comment by peterzhuamazon** [comment]
We just shipped OpenSearch-Java Client 2.0.0 https://repo1.maven.org/maven2/org/opensearch/client/opensearch-java/2.0.0/
