### ISSUE TITLE
[BUG] bulk updates failing with Json RawValue

### ISSUE THREAD

**Issue by Arsnael** [opensearch-project/opensearch-java#165]
Hello guys!

**What is the bug?**
When trying to update parts of documents with a Json RawValue, it fails with a parse exception saying the field we are trying to modify is unknown. However, a same operation with the normal update request seems to work.

**How can one reproduce the bug?**
For example I have this indexed in OpenSearch:  

```
{
  "message": "trying out OpenSearch",
  "field":"Should be unchanged"
}
```

Try to do a bulk update on the field `message` with a Json RawValue:

```
BulkRequest.Builder bulkBuilder = new BulkRequest.Builder();
bulkBuilder.operations(
    op -> op.update(idx -> idx
        .index("index")
        .id("1")
        .document(new RawValue("{\"message\": \"mastering out OpenSearch\"}"))
        .routing("1")
    ));
client.bulk(bulkBuilder.build());
```

Getting the error:
```
org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [x_content_parse_exception] [1:2] [UpdateRequest] unknown field [message]
```

While if I use the normal update method it's fine:
```
client.update(new UpdateRequest.Builder()
    .index("index")
    .id("1")
    .doc(new RawValue("{\"message\": \"mastering out OpenSearch\"}"))
    .routing("1")
    .build());
```

**What is the expected behavior?**
It should work like for a normal update in this case?

**Comment by reta** [comment]
@Arsnael  please check https://github.com/opensearch-project/opensearch-java/issues/64

**Comment by Arsnael** [comment]
@reta thanks for the link... I will try that, even if it potentially means a good extra bunch of changes in the implementation^^'

**Comment by Arsnael** [comment]
@reta I'm sorry but still the same issue at the end unfortunately...

```
final Map<String, Object> updatePart = new TreeMap<>();
updatePart.put("message", "mastering out OpenSearch");

BulkRequest.Builder bulkBuilder = new BulkRequest.Builder();
bulkBuilder.operations(
    new BulkOperation.Builder().update(
        new UpdateOperation.Builder<>()
            .index("index")
            .id("1")
            .document(updatePart)
            .routing("1")
            .build())
        .build());
client.bulk(bulkBuilder.build());
```

Same error message, no field message found for update request... I don't think I made something wrong (but maybe?)

In the issue you linked me it's more about bulk indexing. Is it possible there is something wrong with bulk partial updates regarding this case?

**Comment by Arsnael** [comment]
@reta I confirm it works! Thanks a lot for the support and the explanation :)

**Comment by reta** [comment]
@Arsnael mind closing this one? The documentation on OpenSearch side is accurate [1]

[1] https://opensearch.org/docs/latest/opensearch/rest-api/document-apis/bulk/

**Comment by Arsnael** [comment]
@reta I still find this not really trivial regarding the client but that solved my problem, so sure

**Comment by reta** [comment]
> @reta I still find this not really trivial regarding the client but that solved my problem, so sure

Yeah, me too to be fair, but this could be improved for sure
