### ISSUE TITLE
[FEATURE] Be able to set total number of fields on index

### ISSUE THREAD

**Issue by thejettanderson** [opensearch-project/opensearch-java#171]
### Is your feature request related to a problem?
I cannot using the java client set index.mappings.total_fields.limit on an IndexSettings request, and have to do so manually since my project uses the java client instead of the REST client.

### What solution would you like?
I would like to be able to set the total fields limit for an index, same as number of shards, on the IndexSettings object for an IndexTemplateMapping.

### What alternatives have you considered?
Using the REST client in addition to the java client, but I really don't want to have to use both clients in my project just so I can set the total fields on an index mapping update.

**Comment by wbeckler** [comment]
This is worthwhile to fix. Do you want to propose a PR, or at least a method signature?

**Comment by VachaShah** [comment]
Similar to #379
