### ISSUE TITLE
[FEATURE] Accept null values in arrays

### ISSUE THREAD

**Issue by sag1naev** [opensearch-project/opensearch-java#176]
Fixes: https://github.com/elastic/elasticsearch-java/issues/66
Solution: https://github.com/elastic/elasticsearch-java/pull/68

**Comment by dblock** [comment]
We can accept Apache v2 licensed code (didn't look to check whether that is the case with the linked solution), otherwise please feel free to independently implement the fix and PR it here, noting in the PR that it was done without looking at non-Apache v2 licensed implementations.

**Comment by sag1naev** [comment]
Opened pr: https://github.com/opensearch-project/opensearch-java/pull/191
