### ISSUE TITLE
[PROPOSAL] Remove the strong dependency to jakarta.json-api

### ISSUE THREAD

**Issue by alexisgayte** [opensearch-project/opensearch-java#201]
You have a strong dependency to jakarta.json-api 2.0.1 Which can conflict with other libs.
It doesn't seem to be necessary.

Thanks

**Comment by dblock** [comment]
Thanks @alexisgayte, want to PR a fix?

**Comment by alexisgayte** [comment]
@dblock sorry, I don't have a fix.
But I noticed that you are doing a great job removing dependencies such as log4j.

Just for more context spring-boot conflict with it. it uses 1.1.6.

**Comment by dblock** [comment]
Thanks for the info @alexisgayte, but don't let me stop you from trying to fix it :)

**Comment by alexisgayte** [comment]
Hi @VachaShah,
I don't think this PR will sort this issue out.

The main issue here is that using 2.x version bring retro incompatibility with other frameworks. As of now the current main lib in use for jakarta-json-api is 1.1.6.

Removing jakarta-json-api explicitly from your dependency tree, won't remove the implicit dependency declared with eclipse.parsson.
