### ISSUE TITLE
[FEATURE] Testing compatibility on different platforms

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-java#207]
### Is your feature request related to a problem?
We test our clients for Linux platform but we do not know if these clients work smoothly on platforms like windows/mac etc.
Coming from https://github.com/opensearch-project/opensearch-clients/issues/18

### What solution would you like?
Test the client with most popular platforms and CPU architectures:

- x64
- ARM
- Linux
- Windows
- MacOS

**Comment by dblock** [comment]
I think I merged #208 too fast. Looks like this doesn't run unit tests (it probably should) and those are in https://github.com/opensearch-project/opensearch-java/blob/main/.github/workflows/test-unit.yml.

**Comment by VachaShah** [comment]
Raised PR #210 for adding support in unit tests.

**Comment by VachaShah** [comment]
Done in PRs #208 and #210
