### ISSUE TITLE
[FEATURE] Support HTTP/2

### ISSUE THREAD

**Issue by arunx2** [opensearch-project/opensearch-java#215]
### Is your feature request related to a problem?
No

### What solution would you like?
As the `opensearch-java` library requires Java 11, we can support HTTP/2 as it is much faster and more reliable than HTTP1. HTTP1 loads a single request for every TCP connection, while HTTP2 avoids network delay by using multiplexing. We can either leverage java `HttpClient` or square's `OkHttp` libraries

**Comment by reta** [comment]
@arunx2 see please https://github.com/opensearch-project/OpenSearch/issues/4257

**Comment by dblock** [comment]
What changes do we need to do in this library after the above was merged? @arunx2 want to contribute? At the least we need to document how to enable HTTP/2.

**Comment by reta** [comment]
> What changes do we need to do in this library after the above was merged?

We basically need to introduce HTTP/2 compatible client transports, there are few ways we could approach that:
 - [Migrate client transports to Apache HttpClient / Core 5.x](https://github.com/opensearch-project/OpenSearch/issues/4256) - we that, we would get RestClient / RestHighLevelClient with HTTP/1.1 and HTTP/2 support out of the box
 - Introduce another implementation of the `OpenSearchTransport` (using fe Java's standard `HttpClient`)
Thanks.

**Comment by dblock** [comment]
What do you think we should do @reta ?

**Comment by wbeckler** [comment]
@reta what do you mean by "all supported OpenSearch clients." I would propose that opensearch-java be the only "supported" java client.

**Comment by reta** [comment]
@wbeckler apologies for confusion, there are 3 clients right now: `RestClient`, `RestHighLevelClient` and `opensearch-java`. I think we want is to have OpenSearch and `opensearch-java` to live independent lives (no inter-dependencies in other words). That leaves us with: `RestClient` stays (to be used in core internally), `RestHighLevelClient` is deprecated (and hopefully removed), `opensearch-java`  becomes the official way to connect to OpenSearch clusters from JVM applications.

**Comment by reta** [comment]
@dblock @wbeckler I think we could close this one: in 3.0.0 HTTP/2 is already supported (except AWS transport since it is based on Apache HttpClient 4.x).

**Comment by dblock** [comment]
How about adding in README that this client supports HTTP/2, possibly a section in USER_GUIDE that explains how to use it (does it need to be turned on? does it just work?), and then closing this?

**Comment by reta** [comment]
Documenting the HTTP/2 support with respect to https://github.com/opensearch-project/OpenSearch/issues/4257
