### ISSUE TITLE
[PROPOSAL] Separate generated code or remove "THIS CODE IS GENERATED" comments

### ISSUE THREAD

**Issue by AarjavP** [opensearch-project/opensearch-java#218]
### What are you proposing?
Remove
```
//----------------------------------------------------
// THIS CODE IS GENERATED. MANUAL EDITS WILL BE LOST.
//----------------------------------------------------
```
where it does not make sense, or put the generated source code into a separate directory (source set) for clear separation.

### How did you come up with this proposal?
I was browsing the code to see if I could reuse the models/classes for a kotlin client when I came across many of these comments. From #197 #182 https://github.com/opensearch-project/opensearch-clients/issues/19 I see that the comment may be incorrect, at least for now. 

### What is the user experience going to be?
should be transparent to users of the library, but hopefully this makes the code more maintainable for contributors.

### Why should it be built? Any reason not to?
Maybe keeping common package code together? But I think the benefits of having a separate directory outweigh this point, even if only to make sure the code generator does not overwrite non-generated files.

### What will it take to execute?
time and review

### What are remaining open questions?
I have not yet worked with smithy, so are there any considerations to be made for that given it may be used in the near future?
Also, I am assuming that the entirety of the client is not (or will not be) generated. Is that a correct assumption?

**Comment by AarjavP** [comment]
Should I go ahead and create PR for this?

**Comment by dblock** [comment]
> Should I go ahead and create PR for this?

Please! No permission needed.

**Comment by VachaShah** [comment]
Done in #598
