### ISSUE TITLE
[BUG] Client exposes dynamic_templates option which is not implemented on the server

### ISSUE THREAD

**Issue by pdanelson** [opensearch-project/opensearch-java#252]
### What is the bug?
The `dynamic_templates` parameter for supplying hints to dynamic mapping in bulk requests is implemented in [Elasticsearch 7.13+](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/docs-bulk.html#bulk-api-request-body), but is not implemented in the [latest OpenSearch](https://opensearch.org/docs/2.3/api-reference/document-apis/bulk/#request-body) version. However, the parameter is still exposed on the client, causing confusing errors upon usage.

### How can one reproduce the bug?
Use the client to make a request against an OpenSearch cluster of any version with the `dynamicTemplates` parameter set, eg.

```
var indexOperation = new IndexOperation.Builder<IndexRecord>()
    .index(indexRecord.index())
    .id(indexRecord.id())
    .document(indexRecord)
    .dynamicTemplates(Map.of("field1", "template1"))
    .build();
var bulkRequest = BulkRequest.Builder()
    .operations(List.of(indexOperations))
    .build();
client.bulk(bulkRequest).get();
```

### What is the expected behavior?
I would either expect the request to succeed or the configuration parameter to not be exposed in the client if not supported.

### Do you have any screenshots?
The resulting error:
<img width="1764" alt="image" src="https://user-images.githubusercontent.com/19771958/199050511-30cc1b63-ecd1-4e02-a964-5811761cf07d.png">

**Comment by dblock** [comment]
Thanks for bringing this up @pdanelson, let's remove options that aren't supported, we inherited this from a fork. Care to contribute?
