### ISSUE TITLE
[RELEASE] Release v. Next

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#253]
Please add your +1 if you need a release.

**Comment by oana-danescu-idnow** [comment]
+1

**Comment by abhinav-nath** [comment]
+1

**Comment by tengizalpenidze** [comment]
+1

**Comment by george-trandafir-idnow** [comment]
+1

**Comment by FLORIAN-RICKERT-idnow** [comment]
+1

**Comment by fabien-thebaud-ariadnext** [comment]
+1

**Comment by PeterGrzeschik** [comment]
+1

**Comment by saratvemulapalli** [comment]
Is this a process to understand when we do client releases?

**Comment by dblock** [comment]
@saratvemulapalli No, this is issue is for those who just need a release. 

Related, I'd like us to get to a state where we can release with a click of a button and often. There's already other issues open for that.

**Comment by dblock** [comment]
Closing. Open a new one when you want one.

**Comment by wbeckler** [comment]
I think it's been months since the last opensearch-java release, so all of this release interest is valid and we need to get the release moving.

**Comment by VachaShah** [comment]
[opensearch-java 2.2.0](https://search.maven.org/artifact/org.opensearch.client/opensearch-java/2.2.0/jar) is released.
