### ISSUE TITLE
[FEATURE] dynamic_templates parameter 

### ISSUE THREAD

**Issue by johnchiv** [opensearch-project/opensearch-java#261]
The dynamic_templates parameter for supplying hints to dynamic mapping in bulk requests is implemented in [Elasticsearch 7.13+](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/docs-bulk.html#bulk-api-request-body), but is not implemented in the [latest OpenSearch](https://opensearch.org/docs/2.3/api-reference/document-apis/bulk/#request-body) version. 

Users of OpeSsearch have requested that this feature be added.

**Comment by dblock** [comment]
@johnchiv Is this a Java client or a server ask? I think you want a server-side feature that looks like `dynamic_templates`, which is an open feature request: https://github.com/opensearch-project/OpenSearch/issues/3648. If so let's close this issue here?

**Comment by johnchiv** [comment]
Yes, it's server side and that's the open feature. I'll close the issue here.
