### ISSUE TITLE
[BUG] Auto slicing is not supported for DeleteByQuery, Reindex, and UpdateByQuery

### ISSUE THREAD

**Issue by fs-chris** [opensearch-project/opensearch-java#283]
### What is the bug?
The API does not allow defining auto-slicing for `DeleteByQueryRequest`, `ReindexRequest`, and `UpdateByQueryRequest`.
JavaDoc suggests using 'auto' but only `Long` value is accepted.

```
		/**
		 * The number of slices this task should be divided into. Defaults to 1, meaning
		 * the task isn't sliced into subtasks. Can be set to <code>auto</code>.
		 * <p>
		 * API name: {@code slices}
		 */
		public final Builder slices(@Nullable Long value) {
			this.slices = value;
			return this;
		}

```
### How can one reproduce the bug?
n/a

### What is the expected behavior?
Add support for configuring automatic slicing.

### What is your host/environment?
Linux/Windows, Java 17
OpenSearch server 2.4.0
OpenSearch client 2.1.0

### Do you have any screenshots?
n/a

**Comment by wbeckler** [comment]
This is a good catch. Feel free to submit a PR.
