### ISSUE TITLE
[BUG] Compatibility matrix is missing compatible server versions

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/opensearch-java#285]
### What is the bug?
There is no mention of server version 2.4 here: https://github.com/opensearch-project/opensearch-java/blob/main/COMPATIBILITY.md

It would also be useful to know whether the client can work with older versions of opensearch or elasticsearch, so people can know if they can upgrade their client before upgrading their server.

**Comment by andrross** [comment]
It looks like this has gotten more stale...there's no mention of server 2.4 or 2.5, nor is there a mention of client 2.2.0.

**Comment by AmiStrn** [comment]
This is alarming since I was just about to write an implementation using this client. How is it being tested against the latest versions?

**Comment by dblock** [comment]
Server is following semver, so I don't expect anything to break. We are running integration tests against a matrix in https://github.com/opensearch-project/opensearch-java/blob/main/.github/workflows/test-integration.yml#L19, let's add 2.4 and update the docs. @AmiStrn if you want to beat me to this PR, go for it! @wbeckler I think we need to schedule this work with every release of OpenSearch so we're not behind.

**Comment by AmiStrn** [comment]
Timezones... sure @dblock ill make the change to doc :)

**Comment by AmiStrn** [comment]
@dblock I made the quick change:) thanks for clearing this up for us. ran the tests locally and nothing broke.
