### ISSUE TITLE
Port buffered lookahead for Jackson from elasticsearch-java

### ISSUE THREAD

**Issue by luneo7** [opensearch-project/opensearch-java#337]
### What are you proposing?
I've run in the same high CPU usage with opensearch-java as with elasticsearch-java (https://github.com/elastic/elasticsearch-java/issues/471), there they added a LookAheadJsonParser for Jackson  (https://github.com/elastic/elasticsearch-java/pull/489) to fix that high CPU usage, and the code that the PR changed exists in opensearch-java.
So I propose to port that fix to opensearch-java.

### What problems are you trying to solve?
High CPU usage

**Comment by dblock** [comment]
@luneo7 We will gladly accept a PR if the code comes from anything compatible with the APLv2 license!
