### ISSUE TITLE
HitsMetadata total hits is mandatory, but shouldn't be.

### ISSUE THREAD

**Issue by ls-urs-keller** [opensearch-project/opensearch-java#354]
https://github.com/opensearch-project/opensearch-java/blob/e050cb03d5c90198da98010137460215be31eeea/java-client/src/main/java/org/opensearch/client/opensearch/core/search/HitsMetadata.java#L73

E.g. when creating a NativeQuery using the query builder such as
```
NativeQuery.builder()
   ...
   .withTrackTotalHits(false)
   .build()
```

This results in ` org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'HitsMetadata.total'`
Not tracking the totals is completely valid and can result in better performance when scrolling through the data (e.g. searchafter).

**Comment by dblock** [comment]
Is this a bug in the client or a feature request in the server? Either way maybe you can write a small unit test for this and PR a fix?
