### ISSUE TITLE
[BUG]  Bulk Update Request fails due to inconsistent request body generated by the Java Client

### ISSUE THREAD

**Issue by tnahddisttud** [opensearch-project/opensearch-java#376]
Using the Java API Client’s (version: 2.2.0) `BulkRequest.Builder` and `UpdateOperation.Builder` for building bulk update requests behaves differently as compared to [bulk operation documentation](https://opensearch.org/docs/1.2/opensearch/rest-api/document-apis/bulk/) . Because of this attempting to perform the bulk-update operations using the Java Client results in a `[x_content_parse_exception]`

Built a Bulk request using the following code:

```java
BulkRequest.Builder bulkRequestBuilder = new BulkRequest.Builder();
    ids.forEach(
        id -> {
          UpdateOperation<Movie> updateOperation =
              new UpdateOperation.Builder<Movie>()
                  .index(movie-index)
                  .id(id)
                  .document(Movie.builder().isDeleted(true).build())
                  .build();
          bulkRequest.operations(o -> o.update(updateOperation));
        });
BulkRequest bulkRequest = bulkRequestBuilder.build();
```

The request body being created is:

```json
{"update":{"_id":"f1096b","_index":"movie-index"}}
{"isDeleted":true}
```

But as per the documentation it should look like this:

```json
{"update":{"_id":"f1096b","_index":"movie-index"}}
{ "doc" : {"isDeleted":true}}
```

**Comment by wbeckler** [comment]
This is a good catch. Feel free to offer a PR of a failing test and if you're up for it, a fix.

**Comment by tnahddisttud** [comment]
Hello @wbeckler,
Upon working on the test case, I came to realize that it had already been attended to by #358 and subsequently incorporated into the main branch, so we can close this issue. Would you happen to know when we expect a new release containing this patch?

**Comment by VachaShah** [comment]
> Lets close this. I saw @VachaShah signed up to do a release :)

Yes tracking the release in #380 :)
