### ISSUE TITLE
[FEATURE] Enable Generic HTTP Actions in Java Client

### ISSUE THREAD

**Issue by RLashofRegas** [opensearch-project/opensearch-java#377]
### Is your feature request related to a problem?
Not all requests I need to make to OpenSearch are supported natively by the client. One example is mapping AWS IAM Roles to FGAC roles in the security plug-in. These require doing a post request to the `_plugins/_security` endpoint. Since the client doesn't natively support the `_plugins` endpoint I need to send a generic `PUT` request. Right now the client has generic APIs for `get(...)` and `delete(...)` (NOTE: as I'm looking back at the `get` API even that seems to only support getting documents not generic `GET`...), but it does not have the same for `put(...)` or `post(...)`. These are needed to make it easy for clients to use the OpenSearch client to send all the requests they need to make to the cluster with a single client interface.

### What solution would you like?
Add `PutResponse put(PutRequest request)` and `PostResponse post(PostRequest request)` to the `OpenSearchClient` API.

### What alternatives have you considered?
Right now it seems the only alternative would be to manually create a `PutRequest` class and pass this directly to `transport.performRequest(...)` similar to what is done for the `delete(...)` API [here](https://github.com/opensearch-project/opensearch-java/blob/a924a74e02b2fc6d2d7991f3365ff97e95a20d6b/java-client/src/main/java/org/opensearch/client/opensearch/OpenSearchClient.java#L370).

### Do you have any additional context?
No.

**Comment by harshavamsi** [comment]
@reta would love your feedback on this as well as https://github.com/opensearch-project/opensearch-hadoop/issues/124

**Comment by reta** [comment]
> @reta would love your feedback on this as well as https://github.com/opensearch-project/opensearch-hadoop/issues/124

My apologies  @harshavamsi , I am on vacation at the moment, should be back at the end of upcoming week

**Comment by dblock** [comment]
This is a useful feature!

**Comment by reta** [comment]
@harshavamsi I would agree with you and @dblock that it could be a useful feature, but I would suggest to approach it from the perspective of generic client (as a child client), something along these lines:

```
public class OpenSearchClient extends ApiClient<OpenSearchTransport, OpenSearchClient> {
        ...
	public OpenSearchGenericClient generic() {
		return new OpenSearchGenericClient(this.transport, this.transportOptions);
	}
}
```

The `OpenSearchGenericClient` (or `OpenSearchHttpClient` , ... naming is difficult) would be just a wrapper for get/put/post/head/delete/patch methods. With that, the `OpenSearchClient` would stay clean but would let to issue generic HTTP requests. What do you think?

**Comment by dblock** [comment]
@reta What's the reason you prefer to prevent users from making arbitrary requests? 

In other clients I've seen such as Ruby all API calls are implemented as wrappers of generic HTTP methods, which seems to be appreciated by folks asking for this kind of feature. 

Maybe we can do the opposite, extract `OpenSearchGenericClient` out of `OpenSearchClient` and make `OpenSearchClient extends OpenSearchGenericClient` in a way that the generic methods become private? One could instantiate `OpenSearchGenericClient` to make raw requests?

**Comment by reta** [comment]
@dblock the `OpenSearchClient` is a "typed" version, intended to simplify the integration with OpenSearch by providing request / response models. 

> In other clients I've seen such as Ruby all API calls are implemented as wrappers of generic HTTP methods, which seems to be appreciated by folks asking for this kind of feature.

The users could make any arbitrary requests by just using `client.transport()` directly, nothing for us to do here 

> However if you look into `OpenSearchClient`, it groups the clients by APIs:

```
public class OpenSearchClient extends ApiClient<OpenSearchTransport, OpenSearchClient> {
    public OpenSearchCatClient cat() { ... } 
    public OpenSearchNodesClient nodes() { ... } 
    ...
```

My suggestion was to offer the generic client following such conventions, hope it makes sense.

**Comment by chenqi0805** [comment]
One use case is for ISM APIs: https://opensearch.org/docs/latest/im-plugin/ism/api/. We need the generic HTTP actions and requests to support that

**Comment by harshavamsi** [comment]
> @harshavamsi I would agree with you and @dblock that it could be a useful feature, but I would suggest to approach it from the perspective of generic client (as a child client), something along these lines:
> 
> ```
> public class OpenSearchClient extends ApiClient<OpenSearchTransport, OpenSearchClient> {
>         ...
> 	public OpenSearchGenericClient generic() {
> 		return new OpenSearchGenericClient(this.transport, this.transportOptions);
> 	}
> }
> ```
> 
> The `OpenSearchGenericClient` (or `OpenSearchHttpClient` , ... naming is difficult) would be just a wrapper for get/put/post/head/delete/patch methods. With that, the `OpenSearchClient` would stay clean but would let to issue generic HTTP requests. What do you think?

I like this idea @reta. Let me put together a PR that adds this generic client.

**Comment by dlvenable** [comment]
This sounds like a good idea. If I understand correctly we'd have a new interface to use which looks somewhat like the following?

```
public interface OpenSearchGenericClient {
  <T> T get(String path, Class<T> responseClass);
  <T> T post(String path, Class<T> responseClass, Object request);
  ...
}
```

It might be good to look at existing frameworks like [HttpClient](https://hc.apache.org/httpcomponents-client-5.2.x/current/httpclient5/apidocs/), [WebClient](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.html), and [RestTemplate](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html).

**Comment by harshavamsi** [comment]
Hi @reta, in this implementation how do we de-serialize the response object without knowing the fields in the response? For example, the [GetResponse class](https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/core/GetResponse.java#L114) uses `GetResult` as the de-serializer to parse the incoming response. This obviously contains fields that are unique to `GetResponse`.

**Comment by reta** [comment]
> Hi @reta, in this implementation how do we de-serialize the response object without knowing the fields in the response? For example, the [GetResponse class](https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/core/GetResponse.java#L114) uses `GetResult` as the de-serializer to parse the incoming response. This obviously contains fields that are unique to `GetResponse`.

Hey @harshavamsi , since the client is generic, the requests and responses are also generic: the consumer would need to deserialize the response body (the same goes with request body serialization) to whatever it thinks it should be.

**Comment by RLashofRegas** [comment]
@harshavamsi ElasticSearch already provides a [low-level REST client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/java-rest-low.html) with a generic `performRequest(Request request)` method. I would also recommend checking that out. I have used it and the API is pretty user-friendly. [Source code is here.](https://github.com/elastic/elasticsearch/blob/main/client/rest/src/main/java/org/elasticsearch/client/RestClient.java)

**Comment by reta** [comment]
@dblock I think it falls into "use raw transport" alternative (from description):

> Right now it seems the only alternative would be to manually create a PutRequest class and pass this directly to transport.performRequest(...) ...

The OpenSearchTransport exposes performRequest() to do raw requests

**Comment by dblock** [comment]
> The OpenSearchTransport exposes performRequest() to do raw requests

Ah yes! Someone write a sample :)

**Comment by dlvenable** [comment]
> Hi @reta, in this implementation how do we de-serialize the response object without knowing the fields in the response? For example, the [GetResponse class](https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/core/GetResponse.java#L114) uses `GetResult` as the de-serializer to parse the incoming response. This obviously contains fields that are unique to `GetResponse`.

@harshavamsi ,

Other REST frameworks such as Spring's RestTemplate and WebClient support this by having the call provide the class to serialize to.

Take `GET` for example, you can have a method like the following.

```
<T> T get(String path, Class<T> responseClass);
```

The framework will deserialize into the `responseClass`. It doesn't need to know this in advance. This allows a caller to provide a `Map` or create their own custom domain object for example.

```
Map<String, Object> rootResponse = genericClient.get("/", Map.class);
assertThat(rootResponse.get("name", "opensearch-node1");
assertThat(rootResponse.get("cluster_name", "opensearch-cluster");
```

As it appears the `OpenSearchTransport` can already provide a lot of this, this generic client could be a fairly light wrapper to make it easier to use.

**Comment by dlvenable** [comment]
That is still possible. RestTemplate actually allows for the response to come as a `ResponseEntity<T>` which has the status code, response headers, and body.

When you use it this way, you do not get exceptions.

**Comment by reta** [comment]
> When you use it this way, you do not get exceptions.

I think we should keep API as minimal as possible: this is not a generic HTTP based client.

**Comment by reta** [comment]
@dlvenable  There is a pull request already [1], would be good to consolidate efforts there 

[1] https://github.com/opensearch-project/opensearch-java/pull/415

**Comment by maryama** [comment]
This is something that my team have also had to work around, and would appreciate a solution for. We migrated from elasticsearch, which as someone stated above, does support such requests.

**Comment by rursprung** [comment]
i also need this in order to implement `opensearch-liquibase` (see https://github.com/opensearch-project/opensearch-migrations/issues/148): as i cannot cover all possible use-cases i want to start with a simple "just run any HTTP action you want against OpenSearch" as a liquibase change type (so liquibase is just used to record what was executed but doesn't - yet - abstract away e.g. over different OpenSearch versions (API changes)). i use opensearch-java instead of just using a pure HTTP library to interact with OpenSearch because i also need to store my own data (changeset management). but for this i'm now blocked due to this feature not being present.

**Comment by dblock** [comment]
https://github.com/opensearch-project/opensearch-java/issues/257 is related.

**Comment by reta** [comment]
@VachaShah @dblock @dlvenable mind if I pick this issue up, that would help to unblock the dedicated support of the OpenSearch in Liquibase @rursprung is working on. Thanks folks.

**Comment by tloubrieu-jpl** [comment]
Hello,
We are migrating to OpenSearch Serverless on AWS and we need this feature to be able to search our OpenSearch data, since our schema is dynamically updated depending on the documents which are loaded in OpenSearch. Thanks !
