### ISSUE TITLE
[RELEASE] Release v2.3.0

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-java#380]
Release the next version of opensearch-java with new features and bug fixes.

Requested in:

* https://github.com/opensearch-project/opensearch-java/issues/369#issuecomment-1448724631
* https://github.com/opensearch-project/opensearch-java/issues/376#issuecomment-1446413708
* https://github.com/opensearch-project/opensearch-java/issues/282#issuecomment-1437699098

**Comment by rmertzpfpt** [comment]
Is this release scheduled? Hoping to avoid switching to HLRC due to #282

**Comment by VachaShah** [comment]
> Is this release scheduled? Hoping to avoid switching to HLRC due to #282

@rmertzpfpt Going to release this today :)

**Comment by VachaShah** [comment]
> > Is this release scheduled? Hoping to avoid switching to HLRC due to #282
> 
> @rmertzpfpt Going to release this today :)

Triggered the release workflow, waiting for approvals on #405

**Comment by VachaShah** [comment]
Got approval for the release #406 

The jenkins workflow is failing: https://build.ci.opensearch.org/job/opensearch-java-maven-sign-and-release/26/console

**Comment by VachaShah** [comment]
We are working to fix the issue that is causing the workflow to fail. Once fixed, the artifact should be released.

**Comment by VachaShah** [comment]
Version 2.3.0 is released https://github.com/opensearch-project/opensearch-java/releases/tag/v2.3.0
