### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Alqayev** [opensearch-project/opensearch-java#387]
### What is the bug?
We can't get buckets from NestedAggregate.

### How can one reproduce the bug?
https://forum.opensearch.org/t/nested-aggregation-query-with-java-opensearchclient/12932 - here is short description.

### What is the expected behavior?
I need buckets from NestedQuery

### What is your host/environment?
AWS

### Do you have any screenshots?
I can share record if link info isn't enough

### Do you have any additional context?
Maybe it's not bug, will be feature by us. Need something like that - https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/_bucket_aggregations.html

**Comment by dickdoof** [comment]
hey facing pretty much the same issue with the nested elements and aggregations. anyone with a solution?

**Comment by wbeckler** [comment]
Have you tried the latest. We released v2.2 5 days ago that might have addressed this here: https://github.com/opensearch-project/opensearch-java/issues/197

**Comment by Alqayev** [comment]
Thanks guys for quick response. That was the solution.
