### ISSUE TITLE
[FEATURE] Data Stream Api

### ISSUE THREAD

**Issue by gkozyryatskyy** [opensearch-project/opensearch-java#402]
### Is your feature request related to a problem?
There is data stream functionality of Open Search https://opensearch.org/docs/latest/im-plugin/data-streams/. This functionality cant be used with Open Search Java client.

### What solution would you like?

1. Add data stream api support to Open Search Java client. Something like:
- `client.indices().getDataStream()`
- `client.indices().putDataStream()`
- `client.indices().deleteDataStream()`
2. Add an ability to override `timestamp_field` for `dataStream` at `putIndexTemplate`

### What alternatives have you considered?
Writing my own implementation using `org.opensearch.client.RestClient`

**Comment by VachaShah** [comment]
Thank you @gkozyryatskyy for the feature request. Would you be willing to open a PR for the feature?

**Comment by gkozyryatskyy** [comment]
@VachaShah not for now, but may be in the future if it is not in your plans.

**Comment by tanqiuliu** [comment]
I have created a PR #416 for data stream APIs, which covers the feature you mentioned.
