### ISSUE TITLE
[BUG] Feedback on Java Client documentation

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/opensearch-java#409]
### What is the bug?
We've received customer feedback on the Java Client documentation. Can you please review and suggest a change to the documentation? 

### How can one reproduce the bug?

Comment 1: 
20230302 | /docs/latest/clients/java/ | I'm looking for documentation on using  ApacheHttpClient5Transport, because I don't want to go back to the bad old days of having Lucene as a dependency of the client.

Comment 2: 
20230313 | /docs/2.6/clients/java/ some of the dependencies missing, the code not compiled

Comment 3: 
20230313 | /docs/2.6/clients/java/ | The new version code is not working.

### What is the expected behavior?
Here is the page in question: https://opensearch.org/docs/latest/clients/java/

### What is your host/environment?
n/a

### Do you have any screenshots?
n/a

**Comment by reta** [comment]
> 20230302 | /docs/latest/clients/java/ | I'm looking for documentation on using ApacheHttpClient5Transport, because I don't want to go back to the bad old days of having Lucene as a dependency of the client.

I will take this one, we updated USER_GUIDE.md but not official docs

**Comment by reta** [comment]
Fixed by https://github.com/opensearch-project/documentation-website/pull/3510
