### ISSUE TITLE
[BUG] PutTemplateRequest _DESERIALIZER not able to parse the name

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/opensearch-java#417]
### What is the bug?
Cannot get template name populated through deserializer

### How can one reproduce the bug?
final JsonpMapper mapper = openSearchClient._transport().jsonpMapper();
final JsonpMapper mapper1 = new PreSerializedJsonpMapper();
final Map<String, Object> indexTemplateMap = readIndexTemplate();
 indexTemplateMap.put("name", "test-template");
 indexTemplateMap.put("index_patterns", "test-index-*");
 final String indexTemplate = new ObjectMapper().writeValueAsString(indexTemplateMap);
// Parse byte array to Map
final ByteArrayInputStream byteIn = new ByteArrayInputStream(indexTemplate.getBytes(StandardCharsets.UTF_8));
final JsonParser parser = mapper1.jsonProvider().createParser(byteIn);
 final PutTemplateRequest putTemplateRequest = PutTemplateRequest._DESERIALIZER.deserialize(parser, mapper1);

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by wbeckler** [comment]
Feel free to add a fix. Is this blocking data-prepper?

**Comment by Bfindlay** [comment]
I have also been encountering this.
I have raised a PR https://github.com/opensearch-project/opensearch-java/pull/723
