### ISSUE TITLE
[RELEASE] Release v2.3.1

### ISSUE THREAD

**Issue by AmiStrn** [opensearch-project/opensearch-java#426]
I think this is more of a patch since it is not adding new functionality but fixing the issue that the existing functionality is missing.

Requested in:
- https://github.com/opensearch-project/opensearch-java/issues/413#issuecomment-1484029499

**Comment by AmiStrn** [comment]
@VachaShah is this ok? Or should i be creating the 2.3.1 branch? Is there an automation for that or do i add it manually?

**Comment by VachaShah** [comment]
@AmiStrn I think we will go with version 2.4.0. 2.x has some features as well which can go in a minor version. No need to create a branch, I will trigger the automated release process tomorrow.

**Comment by VachaShah** [comment]
[Version 2.4.0](https://github.com/opensearch-project/opensearch-java/releases/tag/v2.4.0) is released. https://repo1.maven.org/maven2/org/opensearch/client/opensearch-java/2.4.0/

**Comment by AmiStrn** [comment]
Thanks @VachaShah !
