### ISSUE TITLE
[Guide] Index Lifecycle

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-java#428]
Create `guides/index_lifecycle.md` similar to the [Ruby guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/index_lifecycle.md)

You must assure that: 
- All code-blocks, when run from start to finish in order they appear in the guide, do not throw any errors. If you want to demonstrate that certain statements will throw errors, they must be wrapped in a `try/catch` and print out the expected error.
- All code-blocks are properly marked with the language it's written in (i.e.  ` ```ruby `)
- The instructions, though mostly identical to the Ruby guide, are suitable for this repo.

**Comment by govegito** [comment]
Hey @nhtruong, So I want to work on this issue. Please guide me on where to start.

**Comment by nhtruong** [comment]
@govegito For sure! You will create a guide almost identical to the Ruby guide mentioned in the description. You just need to replace the Ruby code with Java code, and make sure that all code blocks can run from start to finish without throwing errors.

**Comment by Tokesh** [comment]
> Hey @nhtruong, So I want to work on this issue. Please guide me on where to start.

Hey @govegito, if that possible, i can help you! 
I'm new contributor here and want try to start my journey :)

**Comment by govegito** [comment]
Hey @nhtruong so i was going through this [doc](https://opensearch.org/docs/latest/clients/java/) for the initial setup and am facing some issues. Is there any updated guide on the same?

**Comment by VachaShah** [comment]
The user guide is reorganized, guides are added and working samples have been added for index operations.
