### ISSUE TITLE
Add features that are not part of upstream

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-java#43]
- [x] Sync with Upstream
- [x] Remove Xpack feature
- [x] Remove docs

**Comment by VachaShah** [comment]
@imRishN Just confirming if the last point in the checklist is done via your PR?

**Comment by imRishN** [comment]
@VachaShah Yes, we have merged the PR to remove the docs

**Comment by VachaShah** [comment]
Thanks @imRishN!
