### ISSUE TITLE
[BUG] dense_vector instead of knn_vector

### ISSUE THREAD

**Issue by rogeriochaves** [opensearch-project/opensearch-java#437]
### What is the bug?

The index builder has the dense_vector property (https://www.javadoc.io/doc/org.opensearch.client/opensearch-java/latest/org/opensearch/client/opensearch/_types/mapping/DenseVectorProperty.html), but dense_vector doesn't actually exists on OpenSearch, only on ES, if I try to use it, I get a 400.

On OpenSearch, it should actually be knn_vector, as it was decided on this RFC (https://github.com/opensearch-project/OpenSearch/issues/3545), but this option is not available

### How can one reproduce the bug?

Kotlin code:

```
        builder
            .properties(indexedProductSemanticVectorKey) { p ->
                p.denseVector(
                    DenseVectorProperty.of { d ->
                        d.dims(1536)
                    }
                )
            }
```

### What is the expected behavior?
To have a knn option available, or that the denseVector one just works

### What is your host/environment?
AWS

**Comment by wbeckler** [comment]
good catch. Feel free to PR a fix.

**Comment by wisocn** [comment]
Bumping this for visibility - got the same exact issue today

**Comment by maltehedderich** [comment]
I am going to start working on this issue now.

**Comment by rogeriochaves** [comment]
this worked well for us in the new version of the lib, thank you very much
