### ISSUE TITLE
[BUG] JacksonJsonpMapper mutates ObjectMapper passed as a dependency

### ISSUE THREAD

**Issue by L00kian** [opensearch-project/opensearch-java#440]
### What is the bug?
When an JacksonJsonpMapper is constructed using either of 
* `JacksonJsonpMapper#JacksonJsonpMapper(ObjectMapper, JsonFactory)`
* `JacksonJsonpMapper#JacksonJsonpMapper(ObjectMapper)`

the passed ObjecMapper instance is mutated in the following way

```
        this.objectMapper = objectMapper
            .configure(SerializationFeature.INDENT_OUTPUT, false)
            .setSerializationInclusion(JsonInclude.Include.NON_NULL);
```

### How can one reproduce the bug?
Try an API and you will see

### What is the expected behavior?
Injected dependencies must not be mutated, otherwise that must be a documented behaviour

**Comment by wbeckler** [comment]
This is a good catch. Would you be willing to add a failing unit test for this?

Also, if this were fixed today, would that possibly break someone's working code who is relying on that mutation? If so, we might need to do a version bump.

**Comment by luneo7** [comment]
Don't think this is the case anymore, if you take a look at the main branch https://github.com/opensearch-project/opensearch-java/blob/7d22a7dab4278e3f6adb8b4d2125f40a624395c0/java-client/src/main/java/org/opensearch/client/json/jackson/JacksonJsonpMapper.java it doesn't mutate the ObjectMapper. Version 2.4.0 also removed that objectmapper mutation.

**Comment by dblock** [comment]
@luneo7 I believe you're correct. Let's close this. Feel free to reopen @L00kian if you disagree.
