### ISSUE TITLE
[BUG] Missing Highlights and SourceConfig properties in MultisearchBody request

### ISSUE THREAD

**Issue by szczepanczykd** [opensearch-project/opensearch-java#441]
### What is the bug?
Cannot provide Highlights and SourceConfig properties using JAVA API in MultisearchBody request.
The MultisearchBody.Builder doesn't have such fields.

### How can one reproduce the bug?
Try to create RequestItem with MultisearchHeader and MultisearchBody containing Highlights.

### What is the expected behavior?
API is extended to support these fields.

### What is your host/environment?
Windows 10
Client version: 2.3.0

### Do you have any screenshots?
Valid API request:
![image](https://user-images.githubusercontent.com/48957041/231207896-c24866df-75ef-451f-ba8f-3b25ebeef468.png)

### Do you have any additional context?
Will create a PR in the next stage

**Comment by harshavamsi** [comment]
Closing via #442
