### ISSUE TITLE
[FEATURE] SearchTemplateResponse should include aggregations and suggest

### ISSUE THREAD

**Issue by eNorby1** [opensearch-project/opensearch-java#456]
The SearchTemplateResponse currently only includes hits, but would be useful if it also had the aggregations and suggest (optional) fields, same as the regular SearchResponse.

**Comment by wbeckler** [comment]
Is it available from the server? As in, is this a client parsing and response object issue, or is it a feature request on the opensearch server?

**Comment by eNorby1** [comment]
It is - from what I can tell the server response is pretty much the same as in a regular SearchResponse. Which makes sense, the template just gets resolved to a regular query (that can include suggestions and aggregations), the response wouldn't be different.

**Comment by bohyunjung** [comment]
+1

@wbeckler
It is a client parsing and response object issue.

We're experiencing the same issue using the OpenSearch Java client - When we make a request using `SearchTemplate`, We cannot access to the `aggregations` filed by `SearchTemplateResponse` while the server response apparently has it.

**Comment by rmertzpfpt** [comment]
+1 for aggregations (honestly, +1 for feature-parity with RHLC).

Would prefer using the java client, but the RHLC seems much more feature-complete.

Given the existing deprecation notice for the RHLC for OS 3.0.0, is there currently a timeline for feature-parity between the two clients?

**Comment by dblock** [comment]
The code generation project (see #318 and #366) should reach parity and some.
