### ISSUE TITLE
Add Developer Guide / Testing requirements

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-java#46]
If a user follows current README, they will see build failure due to integration test. Please update instruction accordingly. Also, add separate sections for unit testing and dev testing steps for developers.

**Comment by VijayanB** [comment]
@madhusudhankonda Will you be able to help us on this task? Thanks

**Comment by CEHENKLE** [comment]
Hey, this seems weird -- rather than update the documentation, shouldn't we fix what's broken (use main as our first merge point, then backport)?  

Is there a reason to do something different the rest of OpenSearch (https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching)?

**Comment by CEHENKLE** [comment]
Closing this one since we trued up the branching strategy to match the documentation :)
