### ISSUE TITLE
[BUG] /_nodes/stats throwing serialization error

### ISSUE THREAD

**Issue by mitalawachat** [opensearch-project/opensearch-java#47]
**What is the bug?**
```
import org.opensearch.clients.opensearch.nodes.StatsRequest;
import org.opensearch.clients.opensearch.nodes.StatsResponse;
...
...
StatsRequest statsRequest = new StatsRequest.Builder().build();
StatsResponse statsResponse = client.nodes().stats(statsRequest);
...
...
```
Throws:
```
jakarta.json.stream.JsonParsingException: Unexpected JSON event 'VALUE_STRING', expected [START_ARRAY]
```

**What is the expected behavior?**
Node stats response.

**Comment by wbeckler** [comment]
Has anyone else gotten StatsRequest to work who can share example code? @mitalawachat is this still not working in the latest version?

**Comment by VachaShah** [comment]
To use `NodesStatsRequest`:

```
NodesStatsRequest statsRequest = new NodesStatsRequest.Builder().build();
NodesStatsResponse statsResponse = client.nodes().stats(statsRequest);
```

which gives the error:

```
Validation failed Missing required property 'Stats.adaptiveSelection'
```

Another example with a specific metric:

```
NodesStatsRequest statsRequest = new NodesStatsRequest.Builder().metric("os").build();
NodesStatsResponse statsResponse = client.nodes().stats(statsRequest);
```

which gives the error:

```
Validation failed Missing required property 'Stats.adaptiveSelection'
```

Will work on fixing this.

**Comment by reta** [comment]
@VachaShah are you looking into it? thanks!

**Comment by VachaShah** [comment]
> @VachaShah are you looking into it? thanks!

@reta Sorry for the delay! I have been on vacation, I was working on this before that but did not get a chance to publish a PR for the same.

**Comment by reta** [comment]
> > @VachaShah are you looking into it? thanks!
> 
> @reta Sorry for the delay! I have been on vacation, I was working on this before that but did not get a chance to publish a PR for the same.

@VachaShah ah sorry about that, @wbeckler was pretty sure you haven't started on that ....

**Comment by VachaShah** [comment]
> > > @VachaShah are you looking into it? thanks!
> > 
> > 
> > @reta Sorry for the delay! I have been on vacation, I was working on this before that but did not get a chance to publish a PR for the same.
> 
> @VachaShah ah sorry about that, @wbeckler was pretty sure you haven't started on that ....

Thats totally fine. Let me know if you want me to work on it, I see you already raised a PR for fixing it :)

**Comment by reta** [comment]
> > > > @VachaShah are you looking into it? thanks!
> > > 
> > > 
> > > @reta Sorry for the delay! I have been on vacation, I was working on this before that but did not get a chance to publish a PR for the same.
> > 
> > 
> > @VachaShah ah sorry about that, @wbeckler was pretty sure you haven't started on that ....
> 
> Thats totally fine. Let me know if you want me to work on it, I see you already raised a PR for fixing it :)

Yeah, I am not sure what is the best way to go - if you moved further along, please feel free to close my pull request. If not, I have one item to do before moving it from draft state - port all IT tests to use `OpenSearchClient` instead of `RHCL` (we have many of those in core). Thanks!

**Comment by VachaShah** [comment]
> > > > > @VachaShah are you looking into it? thanks!
> > > > 
> > > > 
> > > > @reta Sorry for the delay! I have been on vacation, I was working on this before that but did not get a chance to publish a PR for the same.
> > > 
> > > 
> > > @VachaShah ah sorry about that, @wbeckler was pretty sure you haven't started on that ....
> > 
> > 
> > Thats totally fine. Let me know if you want me to work on it, I see you already raised a PR for fixing it :)
> 
> Yeah, I am not sure what is the best way to go - if you moved further along, please feel free to close my pull request. If not, I have one item to do before moving it from draft state - port all IT tests to use `OpenSearchClient` instead of `RHCL` (we have many of those in core). Thanks!

I think you can take over, the changes are the same plus the port that you mentioned. Thank you for taking this up!
