### ISSUE TITLE
[PROPOSAL] Release v2.5.0

### ISSUE THREAD

**Issue by eNorby1** [opensearch-project/opensearch-java#474]
Hi @VachaShah, 
I'm working on a project that needs the changes we added in #462 #465 and would be greatful if we could get a new 2.x release with them soon :) 

Thanks!

**Comment by VachaShah** [comment]
Hi @eNorby1, definitely happy to help! Till we release 2.5.0, you can use the snapshots we publish for the client - [2.5.0-SNAPSHOT](https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/opensearch-java/2.5.0-SNAPSHOT/) which have the latest changes from the 2.x branch.

**Comment by VachaShah** [comment]
opensearch-java client 2.5.0 is released: https://repo1.maven.org/maven2/org/opensearch/client/opensearch-java/2.5.0/
