### ISSUE TITLE
[BUG] misleading samples mentioning classes `IndexSettingsBody` and `PutSettingsRequest` that do not exists

### ISSUE THREAD

**Issue by peter-ponzel** [opensearch-project/opensearch-java#475]
### What is the bug?
according to https://opensearch.org/docs/latest/clients/java/#creating-an-index there should be a class `IndexSettingsBody` and `PutSettingsRequest` but they do not exist

### How can one reproduce the bug?
create a new java spring boot application using initializr and add the following dependencies
```
implementation 'org.opensearch.client:opensearch-rest-client:2.7.0'
implementation 'org.opensearch.client:opensearch-java:2.4.0'

implementation 'software.amazon.awssdk:apache-client:2.20.26'
implementation 'software.amazon.awssdk:sdk-core:2.20.26'
implementation 'software.amazon.awssdk:regions:2.20.62'
```
### What is the expected behavior?
that all classes are found in order to get the sample code running

### What is your host/environment?
opensuse thumbleweed 20230414

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-java/assets/20244744/f96da2c6-b07d-4269-9a49-afc869f0cefc)

### Do you have any additional context?
both aforementioned classes couldn't be found in this github repository at all

**Comment by peter-ponzel** [comment]
apparently it is was as "simple" as changing the code to
![image](https://github.com/opensearch-project/opensearch-java/assets/20244744/ce5dceda-5dec-452c-9000-6c59bda79c7b)

but for the love of it - I'm not able set `analyzer` and `charFilter` - is there any way to change the request body using this client ?
or maybe someone can help me understand how to properly use this API

all I want to achieve is sending this
```
{
    "settings": {
        "analysis": {
            "analyzer": {
                "default": {
                    "filter": [
                        "lowercase",
                        "asciifolding"
                    ],
                    "char_filter": [
                        "underscore"
                    ],
                    "type": "custom",
                    "tokenizer": "standard"
                }
            },
            "char_filter": {
                "underscore": {
                    "mappings": [
                        "_ => -",
                        ". => -"
                    ],
                    "type": "mapping"
                }
            }
        }
    }
}
```

**Comment by peter-ponzel** [comment]
I'd be happy to update the documentation - but I've only solved the first half of the problem so far
I still need to know how I can set the `analyzer` and `charFilter` properly

**Comment by harshavamsi** [comment]
Hi @peter-ponzel, here's an example of how to set the analyzer and charFilter based on your input data:

```java
  CustomAnalyzer customAnalyzer = new CustomAnalyzer.Builder().filter(Arrays.asList("lowercase",
          "asciifolding")).charFilter(Arrays.asList("underscore")).tokenizer("standard").build();
  Analyzer analyzerType = new Analyzer(customAnalyzer);
  Map<String, Analyzer> analyzer = new HashMap<>();
  analyzer.put("default", analyzerType);

  MappingCharFilter mappingCharFilter = new MappingCharFilter.Builder().mappings(Arrays.asList("_ => -",". => -")).build();
  CharFilterDefinition charFilterDefinition = new CharFilterDefinition.Builder().mapping(mappingCharFilter).build();
  CharFilter charFilterType = new CharFilter.Builder().definition(charFilterDefinition).build();

  Map<String, CharFilter> charFilter = new HashMap<>();
  charFilter.put("underscore", charFilterType);

  IndexSettings indexSettings = new IndexSettings.Builder()
          .analysis(new IndexSettingsAnalysis.Builder().analyzer(analyzer).charFilter(charFilter).build()).build();
```

Thanks for bringing up the issue with the documentation, will get a PR in place to fix that.

**Comment by peter-ponzel** [comment]
hello @harshavamsi thank you so much - this is very helpful
