### ISSUE TITLE
[BUG] Error not deserializable for invalid alias in alias request

### ISSUE THREAD

**Issue by patschl** [opensearch-project/opensearch-java#480]
### What is the bug?
When executing an alias request with a non-existing alias (`GET /_alias/alias1`) the error response cannot be deserialized as a JSON object is expected, but the response contains only a string for the `error` field.
An `UnexpectedJsonEventException` is thrown:
`org.opensearch.client.json.UnexpectedJsonEventException: Unexpected JSON event 'VALUE_STRING' instead of '[START_OBJECT, KEY_NAME]'` because the response looks like this:
```
{
  "error" : "alias [nonExistingAlias] missing",
  "status" : 404
}
```

### How can one reproduce the bug?
Request indices for a non-existing alias:
`openSearch.indices().getAlias { request -> request.name("nonExistingAlias") }`

### What is the expected behaviour?
The error response will be deserialized correctly.

### What is your host/environment?
AWS OpenSearch 1.2

### Do you have any additional context?
I'm not quite sure who's at fault here since the error response is very inconsistent.
When doing it the other way around by requesting the aliases for an index (`GET /index-1/_alias`) the error message looks correct with the `error` being a JSON object containing the root cause, which the deserializer also expects in this case.

**Comment by szczepanczykd** [comment]
Hello @patschl,

this issue is a duplicate of: https://github.com/opensearch-project/opensearch-java/issues/301

Please try the latest SNAPSHOT release:
https://github.com/opensearch-project/opensearch-java/issues/301#issuecomment-1544428908

**Comment by patschl** [comment]
Sorry, my bad!
Thank you very much.
