### ISSUE TITLE
[FEATURE] Deprecate totalDataSetSize and totalDataSetSizeInBytes in StoreStats 

### ISSUE THREAD

**Issue by szczepanczykd** [opensearch-project/opensearch-java#497]
### Is your feature request related to a problem?
The totalDataSetSize and totalDataSetSizeInBytes are not returned by the server so we can remove dead code.

### What solution would you like?
Marked as @Deprecated for future removal

### Do you have any additional context?
See this Comment:
https://github.com/opensearch-project/opensearch-java/pull/489#discussion_r1199605622

**Comment by VachaShah** [comment]
Done in #498
