### ISSUE TITLE
[FEATURE] Opensearch 2.7.x client documentation improvements

### ISSUE THREAD

**Issue by firatsivrikaya** [opensearch-project/opensearch-java#499]
### Is your feature request related to a problem?
While I have been checking the documentation of opensearch clients for 2.7.x on [Java client - OpenSearch documentation](https://opensearch.org/docs/latest/clients/java/) I have seen that some of the examples (eg [Java client - OpenSearch documentation](https://opensearch.org/docs/latest/clients/java/#initializing-the-client-with-ssl-and-tls-enabled-using-restclient-transport)) are using
org.apache.hc.client5 and org.apache.hc.core5 packages, but sample program on [Java client - OpenSearch documentation](https://opensearch.org/docs/latest/clients/java/#sample-program) is done with org.apache.http. packages.

### What solution would you like?
Documentation should state that I need a additional third party dependencies to run the example which uses the hc packages.
Also, It would be good if we could see a complete example on the create client part of the developer guide for each versions.
[opensearch-java/USER_GUIDE.md at main · opensearch-project/opensearch-java · GitHub](https://github.com/opensearch-project/opensearch-java/blob/main/USER_GUIDE.md#create-a-client)

### Do you have any additional context?
Version : OpenSearch 2.7.x
OS Forum Question Link : https://forum.opensearch.org/t/opensearch-2-7-x-client-documentation/14424
implementation ‘org.opensearch.client:opensearch-rest-client:2.7.0’
implementation ‘org.opensearch.client:opensearch-java:2.4.0’

PS: There is an extra space on documentation of gradle script (between rest-client and 2.7.0 parts)
dependencies {
  **implementation 'org.opensearch.client:opensearch-rest-client: 2.7.0'**
  implementation 'org.opensearch.client:opensearch-java:2.4.0'
}

Thanks!

**Comment by reta** [comment]
I believe the documentation snippet for 2.x line includes RestClient usage for OpenSearch 3.x line, I will fix that
