### ISSUE TITLE
set javadoc encoding to UTF-8

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-java#50]
Refer comment here: https://github.com/opensearch-project/opensearch-java/pull/49

**Comment by wbeckler** [comment]
If anyone wants to do this, it's still a nice first issue to resolve.

**Comment by meetesh** [comment]
Hi, @wbeckler @VijayanB  I am willing to work on this, can you please assign. Thanks!

**Comment by wbeckler** [comment]
Awesome! I will do

**Comment by dblock** [comment]
https://github.com/opensearch-project/opensearch-java/pull/237

**Comment by meetesh** [comment]
Hi @dblock, I notice that you've closed this issue but the PR i've raised is not merged yet. I had to close my earlier PR due to an issue. Have raised a new PR: #241, Please check.
