### ISSUE TITLE
[FEATURE] OpenSearch 2.3.x documentation sample code correction

### ISSUE THREAD

**Issue by firatsivrikaya** [opensearch-project/opensearch-java#500]
### Is your feature request related to a problem?
Sample program on  https://opensearch.org/docs/2.3/clients/java/#sample-program states that following code block can be used to create index
`//Create the index
    String index = "sample-index";
    CreateRequest createIndexRequest = new CreateRequest.Builder().index(index).build();
    client.indices().create(createIndexRequest);`
This seems to be not correct.

Documentation on https://github.com/opensearch-project/opensearch-java/blob/v2.3.0/USER_GUIDE.md states the correct usage of index creation with following code block
`String index = "sample-index";
CreateIndexRequest createIndexRequest = new CreateIndexRequest.Builder().index(index).build();
client.indices().create(createIndexRequest);`

### What solution would you like?
Client documentation should be corrected by using the same index creation code block defined in user guide

### Do you have any additional context?
implementation 'org.opensearch.client:opensearch-rest-client:2.3.0'
implementation 'org.opensearch.client:opensearch-java:2.4.0'

Thanks.

**Comment by VachaShah** [comment]
Raised PR https://github.com/opensearch-project/documentation-website/pull/4789 to update the documentation on the website.

**Comment by VachaShah** [comment]
Fixed in PR https://github.com/opensearch-project/documentation-website/pull/4789
