### ISSUE TITLE
[BUG] publish to maven local is not publishing sha1 and md5 checksums

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-java#52]
**What is the bug?**
`./gradlew publishToMavenLocal` does not generate the checksums

**How can one reproduce the bug?**
1. /gradlew publishToMavenLocal
2. check the files

**What is the expected behavior?**
sha1 and md5 checksums should be generated

**Do you have any additional context?**
work around has been added here: https://github.com/opensearch-project/opensearch-java/pull/51/files#diff-e21da378399d7f35543533d279a39bf3d1024092580f40330fd8bc56379d6164R87-R109
which can be removed once the checksum generation is handled by gradle

**Comment by dblock** [comment]
Fixed via #187.
