### ISSUE TITLE
[BUG] Documentation issue related to Java client

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/opensearch-java#528]
### What is the bug?
See https://github.com/opensearch-project/opensearch-java/issues/530

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
Moved that issue into https://github.com/opensearch-project/opensearch-java/issues/530. Closing this as dup.
