### ISSUE TITLE
[BUG] AWS OpenSearch is reporting 4xx errors when indexing documents, even though indexing succeeds

### ISSUE THREAD

**Issue by jhg023** [opensearch-project/opensearch-java#533]
### What is the bug?
AWS OpenSearch is reporting one 4xx error for every document being indexed, even though the indexing succeeds.

### How can one reproduce the bug?
1. Create an AWS OpenSearch domain (the node instance type shouldn't matter).

2. Create your `OpenSearchClient`:

```java
var client = new OpenSearchClient(
    new AwsSdk2Transport(
        ApacheHttpClient.builder().build(),
        opensearchHost,
        "es",
        Region.US_WEST_2,
        AwsSdk2TransportOptions.builder().build()
    )
);
```

3. Write your indexing logic:

```java
openSearchClient.index(builder ->
    builder.id(id)
        .index(indexType.getIndexAliasName())
        .opType(OpType.Index)
        .refresh(Refresh.False)
        .requireAlias(true)
        .timeout(Time.of(builder -> builder.time("10s")))
        .document(document)
);
```

4. Invoke the above logic to index a document.

### What is the expected behavior?
I wouldn't expect any 4xx errors to occur, as the indexing succeeds on all shards.

### What is your host/environment?
- AWS OpenSearch 2.5.0 (the latest version AWS supports currently)
- Every index has the default refresh policy (1s)
- I'm using index aliases for all operations

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-java/assets/18515648/78e5371b-3e64-4ba8-80d0-14236fbd8c67)

### Do you have any additional context?
Using this same `OpenSearchClient` object, I'm able to query documents without any 4xx errors occurring - it seems to only occur when indexing new documents.

I have a feeling these 4xx errors are due to some HTTP header that I'm not providing in the `AwsSdk2TransportOptions`, as I think AWS may require certain headers.

I've enabled `Error logs` on the AWS OpenSearch domain, but there don't seem to be any logs for 4xx errors, unfortunately.

I was going to reach out to AWS support regarding this issue, but thought it would be better to ask here first.

Thank you!

**Comment by wbeckler** [comment]
can you share what the 4xx error was? Maybe it's in your cloudwatch.

**Comment by jhg023** [comment]
Unfortunately, there’s no CloudWatch logs whatsoever. I mentioned above
that I’ve already enabled the "Error logs", but nothing is written to
CloudWatch when the 4xx errors occur (other than the test events that
OpenSearch writes when first enabling logs to ensure they’re being
delivered to CloudWatch successfully).

**Comment by wbeckler** [comment]
do you know how to enable log4j logging for the client?

**Comment by jhg023** [comment]
No, I’ve just been manually logging responses myself (which just contain
the number of shards that succeeded/failed). Is there any documentation on
how to do that?

**Comment by wbeckler** [comment]
I couldn't find any docs for opensearch-java, but it was forked from elasticsearch-java, I think v7.10. This might work: https://www.elastic.co/guide/en/elasticsearch/client/java-api/7.10/_log4j_2_logger.html

**Comment by jhg023** [comment]
Makes sense, thank you! I’ll try it out in the morning and see if it can
identify the root cause.

**Comment by jhg023** [comment]
Because my project uses Spring Boot, I attempted to enable trace logging using `logging.level.tracer = TRACE`, but nothing is being logged.

I also tried enabling trace logging for everything using `logging.level.root = TRACE`, but that didn't provide any additional insight into the 4xx errors. The Apache HTTP wire logs to OpenSearch show that the response code is 201.

I think I'll have to open a case with AWS support regarding this.

**Comment by dblock** [comment]
Re: logging. Let's properly document how to do this? I have some logging configuration that works in https://github.com/dblock/opensearch-java-client-demo that could help. I opened https://github.com/opensearch-project/opensearch-java/issues/535, @jhg023 if you want to work through this starting with my sample I can try to help.

Re: 404s. Is any of this reproducible with curl?

**Comment by jhg023** [comment]
I only see the 4xx errors on the AWS OpenSearch console within the "Cluster health" section, as seen in the screenshot supplied in my original post. When I enabled trace logging for every package in my service, I was able to see logs for both the Apache HTTP client and for the OpenSearch client, but there weren't any logs that indicated a 4xx error was occurring.

I have to step away for most of the day, but I'll try manually indexing with `curl` later tonight and get back to you with the result.

**Comment by jhg023** [comment]
Update: I was able to use `curl` to successfully index documents without receiving any 4xx errors, so I knew it was definitely something with the `OpenSearchClient`.

I reached out to AWS support, and they were able to identify the root cause:

> I have also checked the ELB logs to see the specific 4xx errors being thrown:
> elb_status_code Total Count: 8867
> 1 200 7551
> 2 201 658
> 3 404 658
> 4 Other 0
> 
> As seen above they are 404 errors. Looking further into the 4xx errors I have also noted that they all come from the below API:
> 
> HEAD https://<domain-name>:443/<index-alias>/_doc/32955571

As you can see, the `OpenSearchClient` is sending a `HEAD` request alongside every `PUT` request that actually indexes the document, and AWS is only expecting to receive `PUT`

**Comment by dblock** [comment]
So `exists` correctly returns `true` or `false`, but uses `HEAD`, which causes a 404, which is expected? Makes sense. We may want to document this somewhere in the user guide, maybe you'd like to contribute a "check if a document exists" section?

Generally for your application you should probably do some kind of upsert. Checking for a document existence in a distributed system may be eventually consistent ;)

**Comment by jhg023** [comment]
Agreed, I modified my code to use an upsert pattern instead.

I'll see if I can find some time to contribute :)

Thanks again!
