### ISSUE TITLE
[FEATURE] Support bucket size for MultiTermAggregation

### ISSUE THREAD

**Issue by fabiankopatschek** [opensearch-project/opensearch-java#534]
### Is your feature request related to a problem?
_Using the MultiTermAggregation returns the default bucket size of 10. By setting the size parameter (see [Bucket aggregations](https://opensearch.org/docs/latest/aggregations/bucket-agg/#multi-terms)), you could get more buckets. In this library the possibilty is missing to set the "size" parameter. The [MultiTermAggregation](https://github.com/opensearch-project/opensearch-java/blob/2.x/java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/MultiTermsAggregation.java#L54) Object has only the "terms" attribute._

### What solution would you like?
_Add the missing attribute to the MultiTermsAggregation type._

### What alternatives have you considered?
_An alternative could be using any HttpClient library instead._

### Do you have any additional context?
_In this forum post the issue was also addressed by someone else: [No Support to change the default bucket value in MultiTermAggregation](https://forum.opensearch.org/t/no-support-to-change-the-default-bucket-value-in-multitermaggregation/14360)_

_In all the type classes is the hint, that it is generated code. But i could not find any documentation on how or where to set the attribute and generate the type classes. Maybe then i would have done a Pull Request instead of this Feature Request._

**Comment by wbeckler** [comment]
This sounds like a good idea. Feel free to propose an interface, or even better, a test case that would illustrate the correct approach.

**Comment by fabiankopatschek** [comment]
I added the code in my fork. The forked version is used in our production system.
I created a pull request for the changes.
I noticed that the "generated code comment" is no longer applicable [#598](https://github.com/opensearch-project/opensearch-java/pull/598)
I couldn't find any exclusive testcases for this model classes, so there is no new testcase.

**Comment by VachaShah** [comment]
Done via #627
