### ISSUE TITLE
[BUG] "HTTP Status 413 – Payload Too Large" when updating small document

### ISSUE THREAD

**Issue by jhg023** [opensearch-project/opensearch-java#543]
### What is the bug?
I'm seeing the following error when calling the `update` method on a small document (4 KB):

```
at [Source: (byte[])"<!doctype html><html lang="en"><head><title>HTTP Status 413 – Payload Too Large</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 413 – Payload Too Large</h1></body></html>"; line: 1, column: 2]
```

### How can one reproduce the bug?
1. Create your `OpenSearchClient`:

```java
var client = new OpenSearchClient(
    new AwsSdk2Transport(
        ApacheHttpClient.builder()
            .connectionTimeout(Duration.ofSeconds(5)) // Default is 2s
            .maxConnections(100)                      // Default is 50
            .build(),
        opensearchHost,
        "es",
        Region.US_EAST_1,
        AwsSdk2TransportOptions.builder().build()
    )
);
```

2. Perform an upsert into an existing index:

```java
var updateResponse = openSearchClient.update(
    UpdateRequest.of(updateBuilder ->
        updateBuilder.source(SourceConfig.of(builder -> builder.fetch(false)))
            .doc(request.partialDocument())
            .docAsUpsert(true)
            .id(id)
            .index(indexType.getIndexAliasName())
            .refresh(Refresh.False)
            .requireAlias(true)
            .timeout(Time.of(builder -> builder.time("10s")))
    ),
    Object.class
);
```

### What is the expected behavior?
I'd expect the document to be updated (or indexed if it doesn't already exist) in OpenSearch without claiming the payload size is too large.

### What is your host/environment?
 - AWS OpenSearch 2.5.0 (the latest version AWS supports currently)
 - Every index has the default refresh policy (1s)
 - I'm using index aliases for all operations

### Do you have any screenshots?
N/A

### Do you have any additional context?
This error isn't occurring with small documents (~500 bytes), but it occurs with documents around 4 KB and larger.

The error occurs in a service running on Spring Boot, but I've already verified that it isn't caused by configurations in Spring that limit request sizes.

**Comment by jhg023** [comment]
AWS is not reporting any 4xx errors, so I have reason to believe it's something related to the `ApacheHttpClient`

**Comment by jhg023** [comment]
Going to close this for now, as I'd like to do some additional debugging.

**Comment by dblock** [comment]
Feel free to reopen as is. Anything unexpected is a potential bug.

**Comment by jhg023** [comment]
It turned out to not be related to OpenSearch.

I had HTTP/2 enabled in my service, and that seemed to be causing the
issue. I have no idea why it thinks ~3600 bytes is too large of a payload,
so I just changed it to HTTP/1.

Sorry about that!

**Comment by dblock** [comment]
But wait, isn't that a problem? Should OpenSearch not be rejecting payloads of this size? Mind running this down?
