### ISSUE TITLE
[PROPOSAL] Release 2.6

### ISSUE THREAD

**Issue by ajmedury** [opensearch-project/opensearch-java#546]
### What are you proposing?
I'm working on a project that needs the changes we added in #524 and would be grateful if we could get a new 2.x release with them soon.

**Comment by VachaShah** [comment]
Hi @ajmedury, definitely happy to help! Till we release 2.6.0, you can use the snapshots we publish for the client - [2.6.0-SNAPSHOT](https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/opensearch-java/2.6.0-SNAPSHOT/) which have the latest changes from the 2.x branch.

**Comment by wbeckler** [comment]
There is a PR that fleshes out support for knn beyond what was in #524 . That PR is here and is not yet merged:
https://github.com/opensearch-project/opensearch-java/pull/548

I propose that we wait to merge #548 before doing the release.

**Comment by dblock** [comment]
I merged #548, FYI.

**Comment by VachaShah** [comment]
OpenSearch Java client 2.6.0 is now available: https://repo1.maven.org/maven2/org/opensearch/client/opensearch-java/2.6.0/
