### ISSUE TITLE
[BUG] - Request failed [x_content_parse_exception] [highlight] failed to parse field [fields]

### ISSUE THREAD

**Issue by ungeordnet** [opensearch-project/opensearch-java#568]
### What is the bug?
When I send a Search-Request with an Highlight option, the response cannot be parsed because of the following exception:

> 2023-07-07T10:31:01,608Z [http-nio-8082-exec-1] t35tTr4c31D ERROR AbstractOpenSearchRepository:85 - Error while searching:
 org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [x_content_parse_exception] [1:1215] [highlight] failed to parse field [fields]
	at org.opensearch.client.transport.aws.AwsSdk2Transport.parseResponse(AwsSdk2Transport.java:492)
	at org.opensearch.client.transport.aws.AwsSdk2Transport.executeSync(AwsSdk2Transport.java:393)
	at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:191)
	at org.opensearch.client.opensearch.OpenSearchClient.search(OpenSearchClient.java:1302)
	at com.heiland.searchservice.repository.AbstractOpenSearchRepository.makeSearch(AbstractOpenSearchRepository.java:81)

My implementation is as follows:
> final Map<String, HighlightField> fields = new HashMap<>();
    fields.put("idExternal", HighlightField.of(builder -> builder.field("idExternal").postTags(Collections.emptyList()).preTags(Collections.emptyList())));
    return Highlight.of(builder -> builder.fields(fields));`

This implementation shall represent the following query:

`GET index/_search
{
  "highlight": {
    "fields": {
      "idExternal": {
        "post_tags": [""],
        "pre_tags": [""]
      }
    }
  }
}`

### What is the expected behavior?

I expect that the reponse can be parsed and the SearchRepsonse has the field suggest is filled propertly.

### What is your host/environment?

    SpringBoot 3
    opensearch-java v2.6.0
    OpenSearch Domain v2.5

**Comment by wbeckler** [comment]
If you can get hold if it, it would be useful to see a redacted copy of the logged query getting sent by the client

**Comment by ungeordnet** [comment]
Is their a special configuration key to log that kind of query or is setting the loglevel to TRACE enough?

**Comment by ungeordnet** [comment]
Nevermind. I set the log.level to TRACE and got the Request-Body logged out. I have seen, that the request is mapped as:

`	"highlight": {
		"fields": {
			"idExternal": {
				"field": "idExternal",
				"post_tags": [""],
				"pre_tags": [""]
			}
		}
	}`

As we can see, the attribute "field" is set, and that was my mistake. The ticket can be closed ;-)

Thank you for the hint @wbeckler

**Comment by dblock** [comment]
Thanks @ungeordnet. What's your fixed code, for the next person? Anything that can be improved in the docs?

**Comment by ungeordnet** [comment]
Hej @dblock ,

my fixed code is looks like the following:

`final Map<String, HighlightField> fields = new HashMap<>();`
 `fields.put("idExternal", HighlightField.of(builder -> builder.postTags(List.of("")).preTags(List.of(""))));`
`return Highlight.of(builder -> builder.fields(fields));`

Setting the attribute "field" at HighlightField.builder (`builder.field("idExternal")`) was my mistake.
