### ISSUE TITLE
[FEATURE] Publish snapshot build

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-java#57]
**Is your feature request related to a problem?**
opensearch-java-0.2-snapshot should be available in 
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/

**What solution would you like?**
New development should be readily available for consumers

**What alternatives have you considered?**
git clone repo from main, build and publish to maven local. Later use that in dependency.

**Do you have any additional context?**
Similar to OpenSearch

**Comment by dblock** [comment]
Need something similar to https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile#L94-L95

**Comment by dblock** [comment]
This was done in https://github.com/opensearch-project/opensearch-java/pull/187, https://github.com/opensearch-project/opensearch-java/pull/192, and https://github.com/opensearch-project/opensearch-java/pull/196

**Comment by dblock** [comment]
Snapshot builds in https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/opensearch-java/ automatically run, e.g. https://build.ci.opensearch.org/job/opensearch-java-snapshot-release/2/
