### ISSUE TITLE
[FEATURE] Support for Filters in K-NN Query

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/opensearch-java#584]
### Is your feature request related to a problem?
OpenSearch k-NN field support filters and the current k-NN query class(https://github.com/opensearch-project/opensearch-java/issues/539) in the client doesn't support the filters.

Documentation for filters: https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/

### What solution would you like?
Add the support to build the k-NN query clause with filters in the client.

### What alternatives have you considered?
Alternative is to build a query json and use that to do the k-NN query with filters.

### Do you have any additional context?
Please enable the support of k-NN query with filters in all the other clients.

**Comment by Xtansia** [comment]
Hi @navneet1v,
Are you specifically referring to the script scoring method on the docs page you reference? As both the bool filtering and Lucene filtering methods should already be supported by the client.

**Comment by wbeckler** [comment]
I think this PR into the docs isn't showing up in the 2.8 docs because it's unreleaseed:
https://github.com/opensearch-project/documentation-website/pull/4476/files

**Comment by Xtansia** [comment]
@navneet1v I believe the samples I'm adding in https://github.com/opensearch-project/opensearch-java/pull/586/files show that all the filtering methods are supported by the client? Please clarify if there's something else I'm missing

**Comment by Xtansia** [comment]
Closing this issue as the filters are supported by the client and now have documentation.
