### ISSUE TITLE
[FEATURE] serialize requests to JSON

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#588]
### Is your feature request related to a problem?

Add a way to easily serialize queries to JSON for logging.

### What solution would you like?

```java
            IndexRequest<Movie> indexRequest = new IndexRequest.Builder<Movie>()
                    .index(index)
                    .id("1")
                    .document(movie)
                    .build();

            logger.info("JSON: {}", indexRequest.toJson());
```

Working serialization code [here](https://github.com/dblock/opensearch-java-client-demo/blob/to-json/src/main/java/Example.java#L34).

### Do you have any additional context?

From a Slack discussion in https://opensearch.slack.com/archives/C051XNH62KB/p1690396113772759

**Comment by wbeckler** [comment]
Sounds cool. I've seen a few people request this, and it's cleaner than using log4j.
