### ISSUE TITLE
Security plugin endpoints

### ISSUE THREAD

**Issue by dmathieu** [opensearch-project/opensearch-java#59]
**Is your feature request related to a problem?**
The security plugin provides endpoints such as creating users and roles. Those endpoints don't have a client equivalent (it also doesn't look like the security plugin has a client that we can use).

**What solution would you like?**
I would like to be able to create/update/delete users and roles from a high level rest client.

**Comment by wbeckler** [comment]
@dmathieu Why did you close this issue/request? Can we reopen?

**Comment by dmathieu** [comment]
I closed this as stale because there hadn't been any response in a year. If someone in the OpenSearch project wants to reopen it, they can do so.
