### ISSUE TITLE
[BUG] Can't use filter "icu_folding" with "unicode_set_filter"

### ISSUE THREAD

**Issue by MikePieperSer** [opensearch-project/opensearch-java#591]
### What is the bug?
Can't use filter "icu_folding" with "unicode_set_filter".
When try to create an index with this filter settings via java client, the server complains about a **missing** "[".

When I create an index via JSON directly (Dev Tools), then the client throws an exception, when reading the index settings, complaining an **unexpected** "[".

### How can one reproduce the bug?
```java
        // create an index
        CreateIndexRequest createIndexRequest = new CreateIndexRequest.Builder().index(index)
            .settings(b->b
                .analysis(ab -> ab
                    .filter("de_folding", fb -> fb
                        .definition(tfdb -> tfdb
                            .icuFolding(ifb -> ifb
                                .unicodeSetFilter("^äöüÄÖÜß")
                            )
                        )
                    )
                )
            ).build();
        CreateIndexResponse createIndexResponse = client.indices().create(createIndexRequest);

        final GetIndexResponse getIndexResponse = client.indices().get(b -> b
            .index(index + "*")
            .ignoreUnavailable(true)
            .allowNoIndices(true)
            .expandWildcards(ExpandWildcard.Open));
        System.out.println("Get index reponse: " + getIndexResponse);
``` 

### What is the expected behavior?
That the index can be created with this filter and can be read back.

### What is your host/environment?
AWS Opensearch Serverless / java-client 2.6.0

### Do you have any screenshots?
No.

### Do you have any additional context?
No.

**Comment by dblock** [comment]
Looks like a legit bug, want to try and turn it into a (failing) unit test?

**Comment by MikePieperSer** [comment]
The bug is not in the java-client but in AWS Opensearch Serverless.
When creating an index like this:
```
PUT icu_sample
{
  "settings": {
    "analysis": {
      "index": {
        "filter": {
          "swedish_folding": {
            "type": "icu_folding",
            "unicode_set_filter": "[^åäöÅÄÖ]"
          }
        }
      }
    }
  }
}
```
The server creates the index. But then if one tries to get the settings back serverless answers with:
```
GET icu_sample

{
  "icu_sample": {
        "analysis": {
          "index": {
            "filter": {
              "swedish_folding": {
                "type": "icu_folding",
                "unicode_set_filter": [
                  "^åäöÅÄÖ"
                ]
              }
            }
          }
        }
      }
    }
  }
}
```
You see "unicode_set_filter" now became an array.
That means, the java-client is absolutely right to complain.
