### ISSUE TITLE
[BUG] Missing support for "cjk" analyzer

### ISSUE THREAD

**Issue by MikePieperSer** [opensearch-project/opensearch-java#592]
### What is the bug?
For analyzer "cjk" exists no method.

Via REST/JSON I can use the analyzer.

### How can one reproduce the bug?
```java
            // create an index
            CreateIndexRequest createIndexRequest = new CreateIndexRequest.Builder().index(index)
                                                                                    .settings(b -> b
                                                                                        .analysis(ab -> ab
                                                                                            .analyzer("ko_analyzer", aab->aab
                                                                                       >>>>     .cjk()  <<<<
                                                                                            )
                                                                                        )
                                                                                    ).build();
            CreateIndexResponse createIndexResponse = client.indices().create(createIndexRequest);
```

### What is the expected behavior?
That "cjk" analyzer is supported like all the other analyzers.

### What is your host/environment?
AWS Opensearch Serverless / java-client 2.6.0

### Do you have any screenshots?
No.

### Do you have any additional context?
No.

**Comment by dblock** [comment]
Looks like it's not implemented ;( 

Want to try to add it?

**Comment by MikePieperSer** [comment]
Yeah, for sure. I've already looked at it, but the sources seem to be generated. I didn't found the generator. Can you point me into the rigtht direction?

**Comment by Xtansia** [comment]
> Yeah, for sure. I've already looked at it, but the sources seem to be generated. I didn't found the generator. Can you point me into the rigtht direction?

The sources were generated in the past, however currently they are not (there's some initiatives in progress to eventually remediate this). So for the time being any bindings will need to be hand written, it'd be awesome if you're willing to take a go at it. I'm not personally super familiar with the analyzers specifically, but happy to try to answer any questions you might have!
