### ISSUE TITLE
[BUG] IllegalStateException encountered when creating index with mappings

### ISSUE THREAD

**Issue by Daniel-Houston** [opensearch-project/opensearch-java#60]
**What is the bug?**
IllegalStateException encountered when creating index with mappings

**How can one reproduce the bug?**
1. Run opensearch as a docker container on your local machine: `docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -d opensearchproject/opensearch:latest`
2. Using the opensearch-java client version 0.1.0, write and run the following code.

```
public class OpenSearchTest {
    public static void main(String[] args) {
        final CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
        credentialsProvider.setCredentials(
                AuthScope.ANY, new UsernamePasswordCredentials("admin", "admin"));


        RestClient restClient = RestClient.builder(new HttpHost("localhost", 9200, "https")).
                setHttpClientConfigCallback(new RestClientBuilder.HttpClientConfigCallback() {
                    @Override
                    public HttpAsyncClientBuilder customizeHttpClient(HttpAsyncClientBuilder httpClientBuilder) {
                        return httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
                    }
                }).build();
        Transport transport = new RestClientTransport(restClient, new JacksonJsonpMapper());
        OpenSearchClient client = new OpenSearchClient(transport);

        //Create the index
        String index = "sample-index";

        JsonObject mappings = Json.createObjectBuilder()
                .add("_source", Json.createObjectBuilder().add("_enabled", true))
                .add("properties", Json.createObjectBuilder()
                        .add("example_field", Json.createObjectBuilder()
                                .add("type", "boolean")
                                .add("store", true)
        )).build();

        CreateRequest createIndexRequest = new CreateRequest.Builder().index(index).mappings(mappings).build();

        try {
            client.indices().create(createIndexRequest);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
```

You should see the following error at the top of the stack trace: 
`java.lang.IllegalStateException: No ObjectCodec defined for the generator, can only serialize simple wrapper types (type passed org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl)`

**What is the expected behavior?**
Json object is successfully serialized and passed as a mapping to the opensearch service

**What is your host/environment?**
 - OS: [MacOS
 - Version 11.6
 - Plugins

**Comment by Daniel-Houston** [comment]
To add a little more information, I modified my example above slightly to add a json mapper:
```
JsonMapper jsonMapper = JsonMapper.builder().addModule(new JSONPModule()).build();

    Transport transport = new RestClientTransport(restClient, new JacksonJsonpMapper(jsonMapper));
    this.client = new OpenSearchClient(transport);
```

But still found that I had the same error. It looks like there error comes from the fact that the passed jsonMapper is not used in the inner JacksonJsonProvider when creating a generator. I can provide more sample code if needed

**Comment by reta** [comment]
@Daniel-Houston interesting issue, could you please try `JsonbJsonpMapper` instead? 

```
import org.opensearch.client.json.jsonb.JsonbJsonpMapper;
```

**Comment by Daniel-Houston** [comment]
@reta Thanks for the suggestion. Using that mapper as shown below as fixed the problem. Is this a viable long-term solution or do we need to dig more into the JacksonJsonpMapper?

```
Transport transport = new RestClientTransport(restClient, new JsonbJsonpMapper());
```

**Comment by reta** [comment]
@Daniel-Houston Ok, it probably needs some docs update, but `JacksonJsonpGenerator` (which is what `JacksonJsonpMapper` is using) is not supposed to support complex data types. Getting back to your example, you are hitting this exact method (to serialize `mappings`):

```
    // Assumes the jackson-datatype-jsr353 module has been added to the generator
    // see https://github.com/FasterXML/jackson-datatypes-misc/tree/master/jsr-353
    @Override
    public JsonGenerator write(String name, JsonValue value) {
        try {
            generator.writeObject(value);
        } catch (IOException e) {
            throw JacksonUtils.convertException(e);
        }
        return this;
    }
```

Although comment is clear, there is no way to customize the modules used in this chain `JacksonJsonpMapper -> JacksonJsonProvider -> JsonFactory` because `JacksonJsonpMapper` creates `JacksonJsonProvider` internally, without ability to customize it.

```
public JacksonJsonpMapper(ObjectMapper objectMapper) {
    this.provider = new JacksonJsonProvider();
    this.objectMapper = objectMapper;
}
``` 

You have probably noticed, but providing own instance of the `objectMapper` does not help at all, the request serialization uses `provider.createGenerator` instead.

**Comment by Daniel-Houston** [comment]
Good to know, thanks!

**Comment by dblock** [comment]
Thanks for fixing this @reta! https://github.com/opensearch-project/opensearch-java/pull/61

**Comment by reta** [comment]
@Daniel-Houston the PR  is  not merged yet, sadly

**Comment by reta** [comment]
Fixed now :)
