### ISSUE TITLE
[FEATURE] add script_fields to _msearch queries

### ISSUE THREAD

**Issue by ts8ta** [opensearch-project/opensearch-java#617]
### Is your feature request related to a problem?
add "script_fields" to _msearch request

### What solution would you like?
I need a way to add "script_fields" to my msearch request item. It looks like it is already possilbe with a single index seach request, but not in the MultiIndex Search.

**Comment by VachaShah** [comment]
Thank you @ts8ta for raising this issue. Want to try to implement this?

**Comment by ts8ta** [comment]
Hi @VachaShah , thanks for your message. I think I won't be able to look into this myself due to capacity reasons. 

What is the usual way to get this implemented and how long would it take?

**Comment by VachaShah** [comment]
I worked on this to add script_fields to multi search and just raised a draft PR for it. However, for the test I am writing, I keep getting `all shards failed error`. I will look into it further, may be I am not adding the script fields in the test right 🤔 The draft PR is https://github.com/opensearch-project/opensearch-java/pull/632

**Comment by Shiv10122003** [comment]
hello i want to contribute

**Comment by VachaShah** [comment]
> hello i want to contribute

Thank you @Shiv10122003 for your interest! This issue is resolved but we would love your contributions for other issues in the repo. Please check out some of the [good first issues](https://github.com/opensearch-project/opensearch-java/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

**Comment by Shiv10122003** [comment]
thanks VachaShah
