### ISSUE TITLE
Please create additional "good first issues" for OSCI participants

### ISSUE THREAD

**Issue by rednaksi91** [opensearch-project/opensearch-java#621]
Open Source Contributor Initiative (OSCI) launches on September 20th. Java client repo lacks the minimum of 15 "good first issues" that can be picked up by participants of OSCI.

Please create additional "good first issues" to reach the suggested minimum of 15 by 9/15.

**Comment by arsenalzp** [comment]
Hello,
Any progress for providing good-first-issue for those who want to contribute?

**Comment by VachaShah** [comment]
Thank you @arsenalzp for your interest! To start contributing, good first issues are present at https://github.com/opensearch-project/opensearch-java/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
