### ISSUE TITLE
[BUG] Compatibility.md does not include latest versions of OpenSearch

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/opensearch-java#629]
### What is the bug?
Coming from https://forum.opensearch.org/t/java-client-compatibility/15917.

https://github.com/opensearch-project/opensearch-java/blob/main/COMPATIBILITY.md shows compatibility of the latest client up to core v2.6, whereas OpenSearch is on the verge of releasing 2.10.

Can the compatibility.md get updated?

Maybe a script is needed to create an issue when the server bumps, or a script that checks the api specification to see if there are uncovered versions in compatibility.md?

**Comment by VachaShah** [comment]
I will add the new versions to the test matrix and compatibility files.
