### ISSUE TITLE
[BUG] TermvectorsResponse doesn't handle optional elements

### ISSUE THREAD

**Issue by MikePieperSer** [opensearch-project/opensearch-java#639]
### What is the bug?
The termvectors API allows to switch of many fields in the response, like "field_statistics" or "term_statistics" and many others.
But the parser in the client still assumes that all fields are available, which leads to runtime errors.

### How can one reproduce the bug?
Make a _termvectors call with the java-client.

### What is the expected behavior?
No error should appear and the optional fields shall be null.

### What is your host/environment?
Linux

### Do you have any screenshots?
no

### Do you have any additional context?
no

**Comment by VachaShah** [comment]
Done via #642
