### ISSUE TITLE
[BUG] Make id of Hit Nullable

### ISSUE THREAD

**Issue by hubertazg** [opensearch-project/opensearch-java#696]
### What is the bug?
 Executing a search from Java Opensearch client by disabling stored fields ("stored_fields: _none_")  fails with an MissingRequiredPropertyException. Even though, the query is executed by the Opensearch server (confirmed through Opensearch console), the Java client cannot process a response with null `_id` field.

### How can one reproduce the bug?
Create a new query with stored_fields as _none_ and opensearch client will throw an error.
`SearchRequest.Builder searchRequest = new SearchRequest.Builder();
  searchRequest.storedFields("_none_");
  return searchRequest.build();
`
Execute the above search request for any filter/query and you can notice that the Java client throws an `MissingRequiredPropertyException: Missing Required Property 'Hit.id'`

### What is the expected behavior?
Since the query with "_none_" stored fields is executed by opensearch server, the Java client should be able to process it and return the response without throwing an exception.

### What is your host/environment?
Opensearch Java - 2.7.0

### Do you have any screenshots?
![Screen Shot 2023-10-27 at 5 00 18 PM](https://github.com/opensearch-project/opensearch-java/assets/149452540/1c513758-f45b-46ca-8323-e1f2580525c4)

### Do you have any additional context?
Searching & Retrieving documents with id field is  very slow potentially due to reading the id from stored fields. Executing the search by disabling stored fields (by using "stored_fields: _none_") makes the search faster.  However, the Java client cannot process responses with null Id from Opensearch server.

**Comment by dblock** [comment]
Looks like a legit problem. Want to try and write a (failing) unit test for this @hubertazg?
