### ISSUE TITLE
[BUG] Unsupported ICU collation keyword field type

### ISSUE THREAD

**Issue by paverman** [opensearch-project/opensearch-java#721]
### What is the bug?

Using of custom plugin-defined keyword field type [icu_collation_keyword](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-collation-keyword-field.html#_parameters_for_icu_collation_keyword_fields) in the index mapping will lead to an error during response deserialization:

`Missing Required Property Builder.<variant kind>`

Can be reproduced by the following code:
```
index = "index_with_icu_collation_keyword"
GetMappingRequest getMappingsRequest = new GetMappingRequest.Builder().index(index).build();
response = client.indices().getMapping(getMappingsRequest);
```

Index mapping example:

```json
{
    "mappings": {
        "_doc": {
            "dynamic": "strict",
            "properties": {
                "FIELD_NAME": {
                    "copy_to": [
                        "all"
                    ],
                    "store": true,
                    "type": "text",
                    "fields": {
                        "sort": {
                            "type": "icu_collation_keyword"
                        },
                        "keyword": {
                            "type": "keyword"
                        }
                    }
                }
            }
        }
    }
}
```

Seems like this is [known issue ](https://github.com/elastic/elasticsearch-java/issues/249#issuecomment-1150082726)and was fixed in elasticsearch-java sources as a part of [this ](https://github.com/elastic/elasticsearch-java/pull/370)

Perhaps, this is a duplicate of https://github.com/opensearch-project/opensearch-java/issues/611 but with more specific details.

There is a possible [workaround ](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/7.17/missing-required-property.html) but it does not work with [Apache HttpClient 5 Transport](https://opensearch.org/docs/latest/clients/java/) due to a different threads issue.

### How can one reproduce the bug?

Use icu_collation_keyword in your index mapping.

### What is the expected behavior?

The icu_collation field type should be deserialized without errors.

### What is your host/environment?
Windows
OpenSearch Java Client 2.6.0
Java 11

**Comment by Bfindlay** [comment]
You can assgn this to me. I have a fix thats working locally, just need to spend some time writing more tests.

**Comment by paverman** [comment]
@Bfindlay Great, thank you. 
Will this fix be included in next release 2.9.0? What is the approximate date for the next release? Can I find somewhere a build package from the main branch to test this fix without waiting for the release?

**Comment by Bfindlay** [comment]
@paverman not sure on releases, might have to check with one of the maintainers if there is a release scheduled soon.

**Comment by dblock** [comment]
Open a new issue that says "release v. next" and we'll take care of it.

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/opensearch-java/pull/725
