### ISSUE TITLE
[PROPOSAL] Release 2.8.1

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-java#722]
Proposing to release 2.8.1 with https://github.com/opensearch-project/opensearch-java/pull/714 fix (a user is looking for this fix). I think since it is a bug fix, we could release a 2.8.1 instead of a minor increment 2.9.0. There are no other features yet to be released after 2.8.0 beside this fix.

WDYT @dblock @reta?

**Comment by reta** [comment]
+1, thanks @VachaShah !

**Comment by dblock** [comment]
I think we should release as often as necessary! No need to ask.

**Comment by VachaShah** [comment]
Thank you @reta and @dblock! I will work on this release.

**Comment by VachaShah** [comment]
opensearch-java 2.8.1 is released: https://repo1.maven.org/maven2/org/opensearch/client/opensearch-java/2.8.1/
