### ISSUE TITLE
[PROPOSAL] Release #723 and #725 next (ICU keyword and PutTemplate request fixes)

### ISSUE THREAD

**Issue by Bfindlay** [opensearch-project/opensearch-java#734]
### What are you proposing?
Hi! We had two bug fixes merged recently. These are:
https://github.com/opensearch-project/opensearch-java/pull/725
https://github.com/opensearch-project/opensearch-java/pull/723

If possible I would like to propose a release for these two features as the bugs are currently blocking our full utilization of the java-client.

Thanks!

**Comment by reta** [comment]
+ https://github.com/opensearch-project/opensearch-java/issues/720

**Comment by paverman** [comment]
Can anyone give an approximate time for when it will be released?

**Comment by Bfindlay** [comment]
@reta @dblock @VachaShah Is there anything I can do to help get this one released? This is quite a big blocker for us and I am happy to help if you need a hand to get it done.

Thanks!

**Comment by Bfindlay** [comment]
@reta is it possible to get this release done anytime soon? The ICU issue is still a blocker for us.
Thanks!

**Comment by reta** [comment]
> @reta is it possible to get this release done anytime soon? The ICU issue is still a blocker for us.

@Bfindlay somehow lost track of it, sorry about that, created a release issue https://github.com/opensearch-project/opensearch-java/issues/834

**Comment by reta** [comment]
Done https://github.com/opensearch-project/opensearch-java/releases/tag/v2.8.2
