### ISSUE TITLE
Typed keys in aggregation results cannot be switched off

### ISSUE THREAD

**Issue by fs-chris** [opensearch-project/opensearch-java#741]
### What is the bug?
The client always adds a type prefix to aggregation keys in responses which breaks compatibility with other clients or with frontend applications that directly work on aggregation responses.

This is a breaking change compared to other clients' behavior.

The Elasticsearch client API has a switch for turning off that behavior and thus returning compatible results.
See [Serializing aggregations and suggestions without typed keys](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/serialize-without-typed-keys.html)

### How can one reproduce the bug?
Each aggregation result contains aggregation names combined as `[type]#[name]`

### What is the expected behavior?
There should be a compatibility setting that allows returning aggregation names without type prefix like the one provided by Elasticsearch.

### What is your host/environment?
OpenSearch 2.11.0
OpenSearch Java Client 2.8.1
Java 17

### Do you have any screenshots?
![image](https://github.com/opensearch-project/opensearch-java/assets/17310984/8120792f-f343-41fb-91b9-e45f26cc652a)

### Do you have any additional context?
./.

**Comment by dblock** [comment]
This is an awkward feature. Are those typed keys added client or server side? Either way giving the option make sense, want to try to implement it @fs-chris?

**Comment by fs-chris** [comment]
I suppose (without having looked into the code) that this is added by the client. The client prefixes the aggregation's name in the request which then occurs identically in the response, since the server does not touch the aggregation's name. 
So, this simply preserves the type information beyond the request/response round trip.

In the response it is then used for determining the target type before parsing the aggregation's result. I.e., the aggregation's key contains the target type that is used to decide how to parse the actual result body.

**Comment by chanon-onman** [comment]
Hi, is there a way to disable this mechanism in opensearch-java? I got similar problem that type name breaks client applications when migrating from Elasticsearch library to opensearch-java library.

**Comment by Xtansia** [comment]
@chanon-onman I am currently investigating this

**Comment by Xtansia** [comment]
@chanon-onman Support for disabling this has been added as part of v2.18.0, there's an example here: https://github.com/opensearch-project/opensearch-java/blob/main/guides/json.md#disabling-typed-keys-serialization
