### ISSUE TITLE
Bulk UpdateOperation misses upsert options

### ISSUE THREAD

**Issue by fs-chris** [opensearch-project/opensearch-java#744]
### What is the bug?
This is a follow-up for #282 
The update-operation for bulks still misses crucial options like `scriptedUpsert` whereas the common `UpdateRequest` contains these options.
Without `scriptedUpsert` option it's not possible to insert documents by script.

Besides that, the less significant `detectNoop` is also missing.

### How can one reproduce the bug?
n.a.

### What is the expected behavior?
`UpdateOperation` should provide all options that the common `UpdateRequest` provides.

### What is your host/environment?
OpenSearch 2.11
OpenSearch client 2.8.1
Java 17

### Do you have any screenshots?
n.a.

### Do you have any additional context?
n.a.

**Comment by dblock** [comment]
https://github.com/opensearch-project/opensearch-java/pull/748 was merged and reverted because it was made against a 2.8.1 branch which is only for security patches - looking for a PR on main
