### ISSUE TITLE
[BUG] SearchAfter only allows List<Strings> as type.

### ISSUE THREAD

**Issue by ahmadSibai** [opensearch-project/opensearch-java#755]
### What is the bug?
_OpenSearch search request `search_after` must accept any type of variables, in order to be able to paginate using the search_after feature. 
The type defined in `SearchRequest.java` only accepts `List<String>`. This prevents any other non-String sort value from a previous query to be used in the proper type, causing the search query to fail.

The SearchResponse also casts any value from the hits.sort() to String.

### How can one reproduce the bug?
1. Create a query with a `sort` value on a field that is not of type String.
2. Collect the `sort` value of your last hit
3. Create a copy of your first query, but add a `searchAfter` key with value of the List collected in step 2.
4. Notice how these values would have to be of type `String`. Try calling the query and notice how the shards will fail, returning 0 hits.

### What is the expected behavior?
Expected behaviour is for the `sort` value to be in the original type, and for `SearchAfter` to be capable of being of that Type.

### What is your host/environment?
AOSS

### Do you have any screenshots?
No, but you can see [here](https://github.com/opensearch-project/opensearch-java/blob/261cab4cf79e176b0892cfb44fad7c8cfaf44204/java-client/src/main/java/org/opensearch/client/opensearch/core/SearchRequest.java?t=7#L1175C10-L1176C42)

### Do you have any additional context?
_Add any other context about the problem._

**Comment by ahmadSibai** [comment]
Opensearch documentation states that the `search_after` field should have the same values and types of the `sort` field, which can be a non-String. Please see reference [here](https://opensearch.org/docs/latest/search-plugins/searching-data/paginate/#the-search_after-parameter). The examples clearly show how it can be a list of an integer and String.
```
"search_after": [ 1, "32635"],
```

**Comment by dblock** [comment]
Thanks. If you have time, write a test that doesn't compile and maybe see if it's easy to fix?

**Comment by channel-dante** [comment]
close this issue? This issue has been resolved. However, since it is not backward compatible, it will be applied to version 3.x.
