### ISSUE TITLE
leftover references to Elasticsearch

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/opensearch-java#757]
there are some leftover references to elasticsearch in the code (besides the copyright notices & co. which have to stay).

the following regex can find those (with only 1-2 false positives, while filtering out the copyright related ones): `Elasticsearch(?!.*B.V.)(?! licenses)(?! under one or more)` (note: this doesn't work on GitHub, but it e.g. works in IntelliJ)

these should probably be replaced with references to OpenSearch.

**Comment by dblock** [comment]
Yes, please.
