### ISSUE TITLE
[BUG] SearchRequest with suggest property is throwing error

### ISSUE THREAD

**Issue by itshuien** [opensearch-project/opensearch-java#771]
### What is the bug?
_A clear and concise description of the bug._

An error is thrown when making a `SearchRequest` with `suggest`
```
org.opensearch.client.opensearch._types.OpenSearchException: Request failed: [x_content_parse_exception] [1:61] [completion] unknown field [prefix]
```

### How can one reproduce the bug?
_Steps to reproduce the behavior._

```
SearchRequest searchRequest = new SearchRequest.Builder()
        .index(index)
        .suggest(suggest -> suggest.suggesters("completion_text",
                FieldSuggester.of(f -> f.completion(c -> c.field("text").prefix("abc")))))
        .build();

openSearchClient.search(searchRequest, SearchResponse.class);
```

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

The search request should succeed.

### What is your host/environment?
_Operating system, version._

OpenSearch Java Client: `2.8.0`
Java: `17`

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dblock** [comment]
Want to turn this into a failing test?

**Comment by itshuien** [comment]
> Want to turn this into a failing test?

Sorry, I'm not sure if I understand what you mean 😅

**Comment by dblock** [comment]
Write an integration test in this project that makes this API call and fails. This way we know what to fix.

**Comment by VachaShah** [comment]
@itshuien I think the issue is that `prefix` needs to be added to the `FieldSuggester`, this `FieldSuggester` will contain the type of suggester. An example of the usage from the samples: https://github.com/opensearch-project/opensearch-java/blob/main/samples/src/main/java/org/opensearch/client/samples/Search.java#L140-L143. I think this should solve your issue.

**Comment by VachaShah** [comment]
On a separate note, the `prefix` parameter needs to be removed from the completion suggester. I will pick this up.
