### ISSUE TITLE
[FEATURE] Add an integration test that runs on JDK8

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#778]
### Is your feature request related to a problem?

Coming here via https://github.com/opensearch-project/opensearch-java/issues/156, in https://github.com/opensearch-project/opensearch-java/pull/767 we restored support for JDK8, but did not enable CI.

### What solution would you like?

A workflow that exercises the client on JDK8. It could mean building on 11, but executing an integration test on a version 8 runtime.

### What alternatives have you considered?

Let JDK8 support fail without notice.

### Do you have any additional context?

https://github.com/opensearch-project/opensearch-java/issues/156#issuecomment-1865811097

**Comment by reta** [comment]
Thanks @dblock , I will take it, have some ideas on how we could approach that
