### ISSUE TITLE
[BUG] InnerHIt result not containing a _index is throwing Hit.Index missing

### ISSUE THREAD

**Issue by jvan1997** [opensearch-project/opensearch-java#825]
### What is the bug?
_A clear and concise description of the bug._
```
Caused by: org.opensearch.client.util.MissingRequiredPropertyException: Missing required property 'Hit.index'
```
I have a query that I am getting back from opensearch that has a Hit of a parent, and alongside that, I added the option to retrieve all the children of that parent document as Innerhits. 

I've included an example below of the query, where I think it should be getting a parent that has a child document of type `childType`, and then in the innerhits, get the children for it.
```
Query.of {
    it.hasChild {
        it.type("childType")
        it.query {
            it.matchAll { it -> it }
        }
        it.innerHits {
            it.source {
                it.fetch(true)
            }
        }
    }
}
```
Hit.java is able to convert the response to the java class for the parent perfectly fine, however when trying to convert its children, it fails because each InnerHit included with the parent Hit does not have a index specified in the response. I believe it was done under the intention that the the index of the InnerHits should always match the parent, however, the conversion is not aware of the Parent document's index for the InnerHit.

### How can one reproduce the bug?
_Steps to reproduce the behavior._
Reproduction steps would be to create two documents, and associate a parent-child relation to them. And then run a query for a property that would match the parent, and then adding the innerHits field:
```
it.innerHits {
            it.source {
                it.fetch(true)
            }
        }
```
### What is the expected behavior?
_A clear and concise description of what you expected to happen._
Hit.java should be able to convert the InnerHits into Hit objects properly.
### What is your host/environment?
_Operating system, version._
MacOS 14.2.1
### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
I have to wonder why the index is set to mandatory? I did see a discussion on elasticsearch back in 2016 https://github.com/elastic/elasticsearch/issues/18091 but I am not sure if it's the same.

**Comment by Sunhick** [comment]
Starting with elasticsearch v5.0 ```_index```,``` _type```, ```_id``` aren't included with inner nested hits. 

> Nested inner hits will now no longer include _index, _type and _id keys. For nested inner hits these values are always the same as the _index, _type and _id keys of the root search hit.


reference: 
https://github.com/elastic/elasticsearch/blob/v5.4.2/docs/reference/migration/migrate_5_0/search.asciidoc#:~:text=Nested%20inner%20hits%20will%20now%20no%20longer%20include%20_index%2C%20_type%20and%20_id%20keys.%20For%20nested%20inner%20hits%20these%20values%20are%20always%20the%20same%20as%20the%20_index%2C%20_type%20and%20_id%20keys%20of%20the%20root%20search%20hit.

**Comment by VachaShah** [comment]
This is done via #838
