### ISSUE TITLE
[PROPOSAL] Release 2.8.2

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-java#834]
### What are you proposing?
Proposing to release 2.8.2 with https://github.com/opensearch-project/opensearch-java/pull/725 https://github.com/opensearch-project/opensearch-java/pull/723 and other fixes (a user is looking for this fix). 

Any objections @dblock @VachaShah ?

**Comment by dblock** [comment]
No objections!

**Comment by VachaShah** [comment]
None at all!

**Comment by reta** [comment]
https://github.com/opensearch-project/opensearch-java/releases/tag/v2.8.2
