### ISSUE TITLE
[PROPOSAL] Release 2.8.3

### ISSUE THREAD

**Issue by jvan1997** [opensearch-project/opensearch-java#842]
### What are you proposing?
_In a few sentences, describe the feature and its core capabilities._
If possible, can we release 2.8.3 with #838 (#833 should be avoided since we are only using 2.x) it is a change that would enable a new feature for our customers.

Is that an alright process to go through? @dblock @VachaShah

**Comment by VachaShah** [comment]
Another request for `2.8.3` release: https://github.com/opensearch-project/opensearch-java/pull/841

Working on the release.

**Comment by VachaShah** [comment]
https://github.com/opensearch-project/opensearch-java/releases/tag/v2.8.3

**Comment by VachaShah** [comment]
2.8.3 is released.
