### ISSUE TITLE
[BUG] TermsQuery should be a list of terms, not only a single term

### ISSUE THREAD

**Issue by apatrida** [opensearch-project/opensearch-java#86]
**What is the bug?**

TermsQuery is implemented as having a single value, which makes it identical to TermQuery, but in reality it should be a list of values which is the whole purpose of this query type.

**What is the expected behavior?**

The value property should be values, and a vararg list of values to match.

**Do you have any additional context?**
[ES 7.10 docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-terms-query.html)

**Comment by wbeckler** [comment]
This seems right. Does anyone want to submit a PR?

**Comment by VachaShah** [comment]
@apatrida Thank you for creating this issue. Looking at the `TermsQuery`, it has a [TermsQueryField](https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/_types/query_dsl/TermsQuery.java#L56) which has a [list](https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/_types/query_dsl/TermsQueryField.java#L152) as value. 

A related example is https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/test/java/org/opensearch/client/opensearch/integTest/AbstractRequestIT.java#L358.

Let me know if I am missing something here or if this resolves your issue.

**Comment by VachaShah** [comment]
> Shell we close this @VachaShah ?

I think yes, I will close this. @apatrida Please reopen if this does not solve your problem.
