### ISSUE TITLE
[BUG] Upsert in bulk might have some issue

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-java#869]
### What is the bug?
@kkondaka reported that they are facing some issue when using the upsert operation in bulk in data-prepper. https://github.com/opensearch-project/data-prepper/blob/main/data-prepper-plugins/opensearch/src/main/java/org/opensearch/dataprepper/plugins/sink/opensearch/OpenSearchSink.java#L312-L328

### How can one reproduce the bug?
_Steps to reproduce the behavior._

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by VachaShah** [comment]
@kkondaka Can you please add the stack trace here as well? 

@reta I see there was a [fix](https://github.com/opensearch-project/opensearch-java/pull/353/files#diff-106c8d94819a8fcf5625663a3ec7232f8ab4e1266562a65995668c6a1f84b685R435) for upsert in bulk in one of the previous versions. Any suggestions on why the operation might be failing?

**Comment by reta** [comment]
> @reta I see there was a [fix](https://github.com/opensearch-project/opensearch-java/pull/353/files#diff-106c8d94819a8fcf5625663a3ec7232f8ab4e1266562a65995668c6a1f84b685R435) for upsert in bulk in one of the previous versions. Any suggestions on why the operation might be failing?

This interesting, I will take a look shortly

**Comment by VachaShah** [comment]
I thought so too but @kkondaka mentioned that for them id is always present. @kkondaka Can you please add more details here for the error you are seeing?

**Comment by kkondaka** [comment]
We have root caused the issue to a bug in our code. The upsert operation is working as expected. And yes, we always have "id" in these cases even though the code has it as optional. This issue can be closed.

**Comment by VachaShah** [comment]
Great! Thank you @kkondaka for adding the update. Closing this issue.
