### ISSUE TITLE
[FEATURE] Raise errors for HTTP error codes in the generic client

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#927]
### Is your feature request related to a problem?

Coming from https://github.com/opensearch-project/opensearch-java/pull/910#issuecomment-2043122739 I propose we raise errors on non-2xx error codes from the server for the generic client just like in the rest of the java client.

### What solution would you like?

Currently:

```java
// compare with what the low level client outputs
try (Response response = javaClient().generic().execute(...)) {
   if (response.getStatus() != 200) {
      // Request was not successful
   }
}
```

Proposed:

```
// compare with what the low level client outputs
try (Response response = javaClient().generic().execute(...)) {
   // response.getStatus() is always 2xx
} catch(GenericException e) {
  // e.response is a Response
  // e.getStatus() != 2xx
}
```

### What alternatives have you considered?

```java
// compare with what the low level client outputs
try (Response response = javaClient().generic().execute(...)) {
   response.checkErrors() // raises when not 2xx
}
```

### Do you have any additional context?

Let's discuss/implement/close/reject this issue before https://github.com/opensearch-project/opensearch-java/issues/926

**Comment by dblock** [comment]
@reta

**Comment by reta** [comment]
@dblock I would really want to understand why we should do that, in particular what would be the reason to use generic HTTP client vs typed client - if both would do the same thing? (at least with respect to exception handling). We should not forget that, if we decided to pursue this path, the exception should include the response body + status (at least), otherwise we are missing important details.

**Comment by dblock** [comment]
1. Users have asked for a generic client because they can invoke APIs that don't have higher level client support yet, not for more control of error handling.
2. It's less code (easier) to use a client that handles errors for the users.
3. Users will be surprised by the fact that the generic client doesn't behave the same way as the non-generic client.
4. Users that want to handle errors in specific ways will be fewer than users that don't, and those who do can `catch` and handle errors the way they want.
5. As is one cannot easily mix code that uses a generic and a non-generic client because the generic client requires special error handling.
6. All other generic clients in opensearch-py, etc., behave the same way as the non-generic versions of those clients as far as error handling is concerned.

**Comment by dblock** [comment]
> the exception should include the response body + status (at least), otherwise we are missing important details.

I think the exception should include the entire `.response` the same as the response currently returned.

**Comment by reta** [comment]
Fair points, thanks @dblock,  I think we could accommodate both favours while building the client, very roughly something like that:

```
javaClient().generic(Options.throwOnHttpErrors())
```

**Comment by dblock** [comment]
> Fair points, thanks @dblock, I think we could accommodate both favours while building the client, very roughly something like that:
> 
> ```
> javaClient().generic(Options.throwOnHttpErrors())
> ```

Yes, it's certainly acceptable! That's my alternate option. It's still not my preferred, but I would be ok with it. Want to try to PR it?

**Comment by reta** [comment]
> I fully admit I may be in the minority here.

We are :D  But it is good to provide options ....
