### ISSUE TITLE
[BUG] The .order() method of aggregation does not work with composite aggregations

### ISSUE THREAD

**Issue by SavvasUmangKamdar** [opensearch-project/opensearch-java#957]
### What is the bug?
The .order() method of aggregation expects input parameters of Map<> or List<Map> type  only which throws error while doing the composite aggregation.

### How can one reproduce the bug?
` 
Aggregation aggregation = new Aggregation.Builder().terms(aggField -> aggField.field("my_name.keyword").order(Map.of("_key", SortOrder.Desc))).build();
`

This will throw an error when used with composite aggregation. Error:
`
[x_content_parse_exception] [1:125] [composite] failed to parse field [sources]
`
with this root cause
`
[1:137] [terms] order doesn't support values of type: START_ARRAY
`
                
### What is the expected behavior?
I think the .order() method should just accept string values too

### What is your host/environment?
Using opensearch-java library in my spring boot application

### Do you have any additional context?
Pls refer this stackoverflow link for detailed question:
[Link](https://stackoverflow.com/questions/78373328/how-to-sort-the-composite-aggregation-in-elasticsearch-opensearch)

**Comment by consulthys** [comment]
The issue might stem from the fact that the `CompositeAggregationSource` class [expects a `TermsAggregation`](https://github.com/opensearch-project/opensearch-java/blob/main/java-client/src/main/java/org/opensearch/client/opensearch/_types/aggregations/CompositeAggregationSource.java#L52) when `terms` is specified in a composite source, i.e. the same `TermsAggregation` structure that is used when specifying standalone `terms` aggregations and which has a different way of supplying the sort order.

On the server-side, the `TermsValuesSourceBuilder` class [expects a simple `SortOrder` value](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/composite/TermsValuesSourceBuilder.java#L80)

**Comment by SavvasUmangKamdar** [comment]
Hey @consulthys, thanks for replying. It would be helpful if you have any solution on how to handle this case?

**Comment by consulthys** [comment]
@SavvasUmangKamdar It's a bug in the OS Java client that needs to be fixed. `TermsAggregation` needs to be specialized to be used in a `CompositeAggregationSource`

**Comment by dblock** [comment]
@SavvasUmangKamdar want to give it a try? Maybe start by writing a (failing) test for it?

**Comment by SavvasUmangKamdar** [comment]
@dblock sorry but am completely new to opensearch, so not much aware of this!

**Comment by dblock** [comment]
> @dblock sorry but am completely new to opensearch, so not much aware of this!

Totally. Give it a shot though, start with https://github.com/opensearch-project/opensearch-java/blob/main/DEVELOPER_GUIDE.md.

**Comment by aiswaryasridharan** [comment]
Can someone please tell me which version of the client library I should be using to see this fix? I'm seeing this same issue and I'm on 2.8.1, as mentioned here: https://opensearch.org/docs/latest/clients/java/

**Comment by Xtansia** [comment]
Hi @aiswaryasridharan, this was fixed in v2.10.2, and the latest version is v2.22.0

**Comment by aiswaryasridharan** [comment]
@Xtansia thank you! I'll see if we can use the latest 😊
