### ISSUE TITLE
[PROPOSAL] Release 2.10.2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#966]
### What are you proposing?

Release 2.10.2 with https://github.com/opensearch-project/opensearch-java/pull/965.

### What users have asked for this feature?

See #960.

**Comment by reta** [comment]
@dblock mind to wait for https://github.com/opensearch-project/opensearch-java/issues/969 before making a release? thank you

**Comment by VachaShah** [comment]
#967 will also be part of the release. Should we do a 2.11 or 2.10.2?

**Comment by dblock** [comment]
Are there any net new features? I think we did deprecate an API, so maybe 2.11 would be the right number.

**Comment by VachaShah** [comment]
Its 2 bug fixes in this release, no deprecations or net new features. So 2.10.2 would be fine I think. Re-triggering the release.

**Comment by VachaShah** [comment]
2.10.2 is released: https://repo1.maven.org/maven2/org/opensearch/client/opensearch-java/2.10.2/

https://github.com/opensearch-project/opensearch-java/releases/tag/v2.10.2
