### ISSUE TITLE
[BUG] Generic HTTP CLient not working with the `AwsSdk2Transport` 

### ISSUE THREAD

**Issue by BrendonFaleiro** [opensearch-project/opensearch-java#970]
### What is the bug?
This bug is in feature: https://github.com/opensearch-project/opensearch-java/issues/377 where the generic Http actions are enabled. When I try to send the request, I get an `Unhandled endpoint type: 'org.opensearch.client.opensearch.generic.OpenSearchGenericClient$GenericEndpoint'` error. 

This issue is similar to https://github.com/opensearch-project/opensearch-java/issues/969. As mentioned there:
> One reason can be, as I see is that in the PR: https://github.com/opensearch-project/opensearch-java/pull/910/files , the changes are done to [RestClientTransport.java](https://github.com/opensearch-project/opensearch-java/pull/910/files#diff-e2e949ab481bece4c378f9682766ef5a3ae5f86cc3acd182edbcf3c7a19b8a61) and [ApacheHttpClient5Transport.java](https://github.com/opensearch-project/opensearch-java/pull/910/files#diff-f12ae3fa82d4a6a889ffa0a53b76490a4099373506e9d60a225f554a76a1e1ac) , but the changes to AwsSdk2Transport is not done.

### How can one reproduce the bug?
```
    private String searchWithGenericClient(OpenSearchClient openSearchClient) throws IOException {
        Response response = openSearchClient.generic()
                .execute(
                        Requests.builder()
                                .endpoint("/" + {index} + "/_search")
                                .method("POST")
                                .json("{"
                                        + "    \"query\": {"
                                        + "        \"match_all\": {}"
                                        + "    }"
                                        + "}"
                                )
                                .build()
                );
            return response.getBody().get().bodyAsString();
    }
```

Dependency (openesearch-java v2.10.1):
```
       <dependency>
            <groupId>org.opensearch.client</groupId>
            <artifactId>opensearch-java</artifactId>
            <version>2.10.1</version>
        </dependency>
```

Output: 
```
org.opensearch.client.transport.TransportException: Unhandled endpoint type: 'org.opensearch.client.opensearch.generic.OpenSearchGenericClient$GenericEndpoint'
at org.opensearch.client.transport.aws.AwsSdk2Transport.parseResponse(AwsSdk2Transport.java:527) ~[opensearch-java-2.10.1.jar:?]
at org.opensearch.client.transport.aws.AwsSdk2Transport.executeSync(AwsSdk2Transport.java:396) ~[opensearch-java-2.10.1.jar:?]
at org.opensearch.client.transport.aws.AwsSdk2Transport.performRequest(AwsSdk2Transport.java:193) ~[opensearch-java-2.10.1.jar:?]
at org.opensearch.client.opensearch.generic.OpenSearchGenericClient.execute(OpenSearchGenericClient.java:168) ~[opensearch-java-2.10.1.jar:?]
```

### What is the expected behavior?
We need the generic flow to work for AWS opensearch as well. 

Our service currently uses JDK8 and we needed to use the newer client to be compatible with JDK8. We are trying to get the generic client working so that we can use the query strings as created for previous versions.

**Comment by dblock** [comment]
Looks like an exact dup of https://github.com/opensearch-project/opensearch-java/issues/969, or is it different?

Any interest in picking this up?

**Comment by BrendonFaleiro** [comment]
> Looks like an exact dup of #969, or is it different?
> 
> Any interest in picking this up?

This isn't an exact duplicate. In #969 the user gets 403 error. I don't end up with a 403, but I am unable to see the response because there is no support for the Generic Client in the AwsSdk2Transport. I believe @reta has self-assigned #969. I'd like to know if the cause is the same.
