### ISSUE TITLE
Cleanup unused branches

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-java#986]
Coming from https://github.com/opensearch-project/opensearch-clients/issues/64, cleanup unused branches.

For some unused branches we probably want to save state, so maybe note the last revision of any branch being deleted in this issue as it's being closed.

**Comment by VachaShah** [comment]
### Unused branches that can be cleaned up
`backport-848-to-2.x`: 6e7c24037166847cd52fe4ac87bf6171d0f9868e
`revert-777-backport/backport-767-to-2.x`: cb4e79b8fd66dab2b1fefacb156dec581de8363f
`backport/backport-442-to-2.x`: 43bb2257323e8e062a8ad01d03d43678bdda0c50
`backport/backport-333-to-2.x`: 57cb3f6ea5738c5a92ce060838204e6006fb9770
`former-main`: 50fb70d2f76e1c88b54e1602069714fb72ccb69f
`revert-70-main`: f868808a4d9e5ae113771c61352d023e8389bfdb

### Release branches
`main`
`2.x`
`2.10.3`
`2.10.2`
`2.10.1`
`2.10.0`
`2.9.1`
`2.8.4`
`2.8.3`
`2.8.2`
`2.8.1`
`1.x`
`2.0`
`1.0.0`
`0.2.1`: c4f674cad2cb7f433567039249453f66ae0e2c47
`0.1`: 30c01a8b6018d3f1af0888b5e46dafee2973f996
`0.1.2`: 629b82782f59c1c0e211f3545cdd18a5c532139b
`0.2`: 00e970880856f4de0f2502b1b9b8c88a195e0a94
`0.1.1`: 3456b73884f2fe745263690148f5ce7b84c4914f
`0.1.x`: b6b8447ba8f463cf39dfef81503148b5b5eb6a86

**Comment by VachaShah** [comment]
@dblock I think we can also clean up the 0.x.x branches which are associated with the release. WDYT?

**Comment by gaiksaya** [comment]
Deleted all unused branches mentioned above except `former-main` as instructed by @VachaShah. Thanks for 2PR.

**Comment by VachaShah** [comment]
Thank you @gaiksaya! I moved `former-main` now to the other non-deleted section. Will close this issue.

@dblock Let us know if you think there are other branches that needs to be deleted.

**Comment by dblock** [comment]
Anything unused can be deleted. Old branches from which a release was created and there's a tag that points to the same point can be deleted too.
