### ISSUE TITLE
[RELEASE] Release 2.10.3

### ISSUE THREAD

**Issue by BrendonFaleiro** [opensearch-project/opensearch-java#988]
Can we release the changes we currently have? I am blocked on the fix for #969.

**Comment by reta** [comment]
@dblock @VachaShah no objections?

**Comment by VachaShah** [comment]
None at all!

**Comment by dblock** [comment]
Go for it.

**Comment by reta** [comment]
https://github.com/opensearch-project/opensearch-java/releases/tag/v2.10.3
